#!/usr/bin/env ruby

require 'mysql'

NUMLOGS = 1000
NUMQSOS = 150000
NUMALLMULTS = 5

CALLSIGNS = [ "2E0ZRQ",
              "3D2A",
              "3D2C",
              "3G3M",
              "4A2S",
              "6Y1V",
              "8P5A",
              "9A1A",
              "9A5Y",
              "9K2GS",
              "9K2K",
              "9Y4W",
              "AA0A",
              "AA0AW",
              "AA0N",
              "AA1K",
              "AA3B",
              "AA4NN",
              "AA4RP",
              "AA4V",
              "AA5B",
              "AA6DX",
              "AA6F",
              "AA6K",
              "AA6PW",
              "AA6YX",
              "AB0S",
              "AB0YM",
              "AB1KW",
              "AB1NJ",
              "AB2NI",
              "AB2TS",
              "AB2TS",
              "AB3CX",
              "AB3RS",
              "AB3UM",
              "AB4GG",
              "AB5ZA",
              "AB7E",
              "AB7R",
              "AB9DU",
              "AB9H",
              "AB9QT",
              "AC0C",
              "AC0D",
              "AC0DS",
              "AC0IF",
              "AC0QG",
              "AC0UR",
              "AC0W",
              "AC0XR",
              "AC1J",
              "AC4BB",
              "AC50",
              "AC5O",
              "AC5O",
              "AC7GI",
              "AC7SG",
              "AC8E",
              "AD1DX",
              "AD4EB",
              "AD4L",
              "AD5XD",
              "AD6E",
              "AD6GN",
              "AD6MF",
              "AD6NF",
              "AD6X",
              "AD6Z",
              "AD7LF",
              "AD7SH",
              "AD7ZQ",
              "AD8B",
              "AE1P",
              "AE1T",
              "AE5FZ",
              "AE5PW",
              "AE5T",
              "AE6RF",
              "AE6Y",
              "AE6YB",
              "AE7CD",
              "AE7EE",
              "AE7G",
              "AE7KL",
              "AF1T",
              "AF6EV",
              "AF6JG",
              "AG5Z",
              "AG6EF",
              "AG6KG",
              "AH7C",
              "AI5M",
              "AJ3T",
              "AJ6V",
              "AJ9C",
              "AK1P",
              "AK1W",
              "AK6M",
              "AK7AT",
              "AK7EE",
              "AL1G",
              "AL7GA",
              "AL9A",
              "BV7RC",
              "C5A",
              "C6AKQ",
              "CE2",
              "CE4CT",
              "CK8G",
              "CN2R",
              "CO2GL",
              "CQ9T",
              "CR3A",
              "CR3L",
              "CR3T",
              "CR6K",
              "CU2KG",
              "D4C",
              "DK6CS",
              "DL1CA",
              "DL3TD",
              "DM1A",
              "DR1A",
              "DS1DLS",
              "DU1BP",
              "E51NOU",
              "E73M",
              "E73W",
              "EA1ABT",
              "EA3WD",
              "EA4KD",
              "EA5RS",
              "EA5UB",
              "EA8AQV",
              "EB8AH",
              "ED3T",
              "EF8HQ",
              "EF8M",
              "EF8R",
              "EI9E",
              "F6DKQ",
              "F6KHM",
              "F6KNB",
              "F8RZ",
              "FM5GB",
              "FY5KE",
              "G0HDB",
              "G0KOC",
              "G2W",
              "G3JKN",
              "G3XAP",
              "G5FZ",
              "GI5K",
              "GM0FSV",
              "GW3KJW",
              "GW4BLE",
              "HA0NAR",
              "HB9DUR",
              "HD2A",
              "HG6W",
              "HI3K",
              "HI3TT",
              "HK1R",
              "HQ9R",
              "IQ1RY",
              "IR4X",
              "IR9Y",
              "JA0JHA",
              "JA1PJS",
              "JA1PVX",
              "JA1RZD",
              "JA1XMS",
              "JA1YPA",
              "JA2XYO",
              "JA3HB",
              "JA3USA",
              "JA3YBK",
              "JA5FDJ",
              "JA7BME",
              "JA7BVS",
              "JA7MJ",
              "JA7NVF",
              "JA7XBG",
              "JA8JMG",
              "JA8RWU",
              "JE1ZWT",
              "JH1CJY",
              "JH3OWW",
              "JH4UYB",
              "JI2ZEY",
              "JI2ZJS",
              "JM1XCW",
              "JO1WKO",
              "JS3CTQ",
              "K0AD",
              "K0ARY",
              "K0AZ",
              "K0BJ",
              "K0BUD",
              "K0BX",
              "K0DEQ",
              "K0DMX",
              "K0DQ",
              "K0DU",
              "K0EA",
              "K0EJ",
              "K0ETV",
              "K0EU",
              "K0FJ",
              "K0FVF",
              "K0GKD",
              "K0GND",
              "K0GUN",
              "K0HB",
              "K0HC",
              "K0HFW",
              "K0HW",
              "K0IP",
              "K0KE",
              "K0LS",
              "K0LUZ",
              "K0MC",
              "K0MD",
              "K0NE",
              "K0OB",
              "K0OU",
              "K0PC",
              "K0PT",
              "K0PVW",
              "K0PY",
              "K0RDW",
              "K0RF",
              "K0RH",
              "K0TI",
              "K0TO",
              "K0TV",
              "K0TW",
              "K0UK",
              "K0VBU",
              "K0VXU",
              "K1BAA",
              "K1BG",
              "K1BX",
              "K1GU",
              "K1GUN",
              "K1KD",
              "K1KP",
              "K1LT",
              "K1LZ",
              "K1MVM",
              "K1PL",
              "K1PT",
              "K1PY",
              "K1RM",
              "K1RX",
              "K1SFA",
              "K1TO",
              "K1TR",
              "K1XM",
              "K1ZZI",
              "K2BSA",
              "K2DB",
              "K2H",
              "K2KR",
              "K2LE",
              "K2PO",
              "K2PO",
              "K2QB",
              "K2QMF",
              "K2RD",
              "K2TJ",
              "K2UF",
              "K2XR",
              "K2ZFD",
              "K3ATO",
              "K3AXR",
              "K3CR",
              "K3FIV",
              "K3LR",
              "K3MD",
              "K3MIM",
              "K3MM",
              "K3PZN",
              "K3SEW",
              "K3TM",
              "K3WA",
              "K3WT",
              "K3WW",
              "K3ZQ",
              "K4AB",
              "K4AMC",
              "K4B",
              "K4BAI",
              "K4BP",
              "K4BX",
              "K4CX",
              "K4EA",
              "K4EU",
              "K4FCC",
              "K4FJ",
              "K4FT",
              "K4FXN",
              "K4GB",
              "K4GMH",
              "K4HAL",
              "K4IQJ",
              "K4LRP",
              "K4NO",
              "K4NV",
              "K4PJ",
              "K4PJO",
              "K4RG",
              "K4RO",
              "K4RZR",
              "K4SSU",
              "K4SWJ",
              "K4TS",
              "K4VV",
              "K4WBM",
              "K4XU",
              "K4YFW",
              "K4ZGB",
              "K5AM",
              "K5ARH",
              "K5CM",
              "K5D",
              "K5DU",
              "K5ENS",
              "K5EOK",
              "K5ER",
              "K5GO",
              "K5KG",
              "K5MR",
              "K5MV",
              "K5NA",
              "K5NZ",
              "K5QNK",
              "K5RKS",
              "K5RQ",
              "K5SL",
              "K5TA",
              "K5TR",
              "K5TXG",
              "K5WA",
              "K5WMH",
              "K5WPN",
              "K5XA",
              "K5XR",
              "K5YAA",
              "K5ZD",
              "K5ZY",
              "K6AAX",
              "K6AM",
              "K6BR",
              "K6DGW",
              "K6DKY",
              "K6EU",
              "K6EZ",
              "K6GAK",
              "K6GEP",
              "K6GHA",
              "K6GT",
              "K6HGF",
              "K6IF",
              "K6IV",
              "K6JAT",
              "K6JJ",
              "K6JRA",
              "K6JRN",
              "K6JS",
              "K6KLY",
              "K6LA",
              "K6LL",
              "K6LRG",
              "K6LRN",
              "K6MM",
              "K6MMM",
              "K6NA",
              "K6ND",
              "K6NDV",
              "K6OO",
              "K6OQK",
              "K6OY",
              "K6PJ",
              "K6RB",
              "K6RIM",
              "K6RM",
              "K6SB",
              "K6SRZ",
              "K6SU",
              "K6SV",
              "K6SXA",
              "K6TS",
              "K6TU",
              "K6VAR",
              "K6VNG",
              "K6VVA",
              "K6WC",
              "K6XN",
              "K6XV",
              "K6XX",
              "K6YL",
              "K6YRU",
              "K6YT",
              "K6Z",
              "K6ZM",
              "K7ACS",
              "K7BG",
              "K7BTW",
              "K7CF",
              "K7EAR",
              "K7FLI",
              "K7HP",
              "K7IA",
              "K7INA",
              "K7JBQ",
              "K7JJM",
              "K7KAR",
              "K7KDX",
              "K7KEV",
              "K7KU",
              "K7LY",
              "K7MKL",
              "K7MO",
              "K7MSC",
              "K7MVA",
              "K7NAL",
              "K7NCR",
              "K7NJ",
              "K7OX",
              "K7PEH",
              "K7RDG",
              "K7RE",
              "K7RF",
              "K7RI",
              "K7RL",
              "K7RR",
              "K7SCX",
              "K7SS",
              "K7SWW",
              "K7TLP",
              "K7TQ",
              "K7UDG",
              "K7UM",
              "K7UT",
              "K7VIT",
              "K7VT",
              "K7VU",
              "K7XC",
              "K7XV",
              "K7ZO",
              "K7ZSD",
              "K8AO",
              "K8BL",
              "K8BZ",
              "K8CXM",
              "K8IA",
              "K8MP",
              "K8PO",
              "K8T",
              "K8TOM",
              "K8WT",
              "K8YM",
              "K8ZOG",
              "K9AIH",
              "K9BGL",
              "K9CT",
              "K9DU",
              "K9GAJ",
              "K9GX",
              "K9JM",
              "K9MMS",
              "K9MWM",
              "K9NR",
              "K9NS",
              "K9NW",
              "K9OHI",
              "K9OM",
              "K9QVB",
              "K9QVB",
              "K9SD",
              "K9SG",
              "K9TM",
              "K9UF",
              "K9WWT",
              "K9WZB",
              "K9XD",
              "K9XL",
              "K9YC",
              "KA0PQW",
              "KA1ARB",
              "KA1GMN",
              "KA1IOR",
              "KA2BSK",
              "KA2HHB",
              "KA6BIM",
              "KA8SYV",
              "KB0HH",
              "KB0NAZ",
              "KB1QYS",
              "KB1UUB",
              "KB5GA",
              "KB6LI",
              "KB6TM",
              "KB7PYF",
              "KB7Q",
              "KB7RLY",
              "KB9AIT",
              "KB9OWD",
              "KB9UWU",
              "KC0DEB",
              "KC0EM",
              "KC0W",
              "KC0ZHF",
              "KC1HD",
              "KC1SQ",
              "KC2CK",
              "KC2HTV",
              "KC2KY",
              "KC4HW",
              "KC4RP",
              "KC6MIE",
              "KC6OVG",
              "KC7ZFP",
              "KC8EO",
              "KC8YVP",
              "KC9ECI",
              "KC9HEK",
              "KC9LDO",
              "KC9LZV",
              "KC9NWE",
              "KC9WC",
              "KD0AGX",
              "KD0R",
              "KD0S",
              "KD4D",
              "KD4POJ",
              "KD5J",
              "KD5MMM",
              "KD5NDU",
              "KD5NRO",
              "KD5PYC",
              "KD6LIL",
              "KD6WKY",
              "KD7HRJ",
              "KD7HZW",
              "KD7JRN",
              "KD7RX",
              "KD7US",
              "KD7YZ",
              "KD8BIN",
              "KD8EZS",
              "KD8IIC",
              "KD8LAV",
              "KD8OTT",
              "KD9MS",
              "KE0L",
              "KE0UI",
              "KE0WO",
              "KE1AF",
              "KE1B",
              "KE2DX",
              "KE2VB",
              "KE3X",
              "KE4MJ",
              "KE4TB",
              "KE5CNS",
              "KE5LLM",
              "KE5NYZ",
              "KE5OG",
              "KE5OVE",
              "KE5RFR",
              "KE5ZZN",
              "KE6FQC",
              "KE6KYI",
              "KE6QR",
              "KE7ADU",
              "KE7DZW",
              "KE7FBY",
              "KE7GKM",
              "KE7HMS",
              "KE7JIW",
              "KE7KUS",
              "KE7MJT",
              "KE7RLI",
              "KE7VSC",
              "KE7WVV",
              "KE7ZGQ",
              "KE9I",
              "KF0F",
              "KF0UR",
              "KF1D",
              "KF2GQ",
              "KF4BI",
              "KF5BPO",
              "KF5CJI",
              "KF5DQZ",
              "KF5FUZ",
              "KF5S",
              "KF6H",
              "KF6RCP",
              "KF6SJ",
              "KF6T",
              "KF7GNI",
              "KF7JGF",
              "KF7P",
              "KF7TBJ",
              "KG0F",
              "KG5VK",
              "KG6C",
              "KG6MZS",
              "KG8OC",
              "KH6",
              "KH6",
              "KH6",
              "KH6FT",
              "KH6GMP",
              "KH6LC",
              "KH6MB",
              "KH6SAT",
              "KH6TE",
              "KH6ZM",
              "KH7B",
              "KH7BB",
              "KH7S",
              "KH7X",
              "KH7XS",
              "KH7Y",
              "KI1G",
              "KI2G",
              "KI4GUO",
              "KI4PAQ",
              "KI4SMP",
              "KI4UMX",
              "KI6GVM",
              "KI6QDH",
              "KI6VC",
              "KI6WD",
              "KI6WOX",
              "KI6YAA",
              "KI7MT",
              "KI7PY",
              "KI9A",
              "KJ2U",
              "KJ3L",
              "KJ3X",
              "KJ4DGT",
              "KJ4JEK",
              "KJ4R",
              "KJ4VTH",
              "KJ5T",
              "KJ6CDA",
              "KJ6GTA",
              "KJ6HBY",
              "KJ7HQ",
              "KJ9C",
              "KK1KW",
              "KK1L",
              "KK5I",
              "KK6MC",
              "KK7AC",
              "KK7CG",
              "KK7OO",
              "KK7PR",
              "KK9V",
              "KL2R",
              "KL5DX",
              "KL5E",
              "KL7AF",
              "KL7CWN",
              "KL7FH",
              "KL7J",
              "KL7LF",
              "KL7OU",
              "KL7QW",
              "KL7RA",
              "KL7SB",
              "KL7WV",
              "KM0O",
              "KM2O",
              "KM4DR",
              "KM5GH",
              "KM5Q",
              "KM6I",
              "KM9P",
              "KN4JX",
              "KN5O",
              "KN7T",
              "KO7X",
              "KP2M",
              "KP4BD",
              "KQ7W",
              "KR4RO",
              "KR5V",
              "KR7X",
              "KS0AA",
              "KS3F",
              "KS5Z",
              "KS7T",
              "KT0A",
              "KT0DX",
              "KT0R",
              "KT3Y",
              "KT4ZB",
              "KT5J",
              "KU0G",
              "KU1CW",
              "KU1T",
              "KU2M",
              "KU4FO",
              "KU8Q",
              "KV0K",
              "KV2M",
              "KV6O",
              "KW7E",
              "KW7XX",
              "KW8N",
              "KX0O",
              "KX7M",
              "KY0R",
              "KY4J",
              "KY5R",
              "KZ2I",
              "KZ2V",
              "KZ4G",
              "KZ5A",
              "KZ5J",
              "LA9Z",
              "LN9Z",
              "LP1H",
              "LP2F",
              "LS1D",
              "LT1F",
              "LU1MA",
              "LU1SAM",
              "LU1XPK",
              "LU3HS",
              "LX7I",
              "LY600A",
              "LY7A",
              "M6T",
              "MD2C",
              "MM0AMW",
              "N0AT",
              "N0BUI",
              "N0CKT",
              "N0FYF",
              "N0GF",
              "N0IJ",
              "N0KE",
              "N0MA",
              "N0NEU",
              "N0NI",
              "N0OB",
              "N0OJ",
              "N0POH",
              "N0QO",
              "N0RPI",
              "N0SMX",
              "N0SXX",
              "N0TA",
              "N0TAF",
              "N0UD",
              "N0UNL",
              "N0XR",
              "N1FS",
              "N1GB",
              "N1IPA",
              "N1LN",
              "N1NEC",
              "N1OXA",
              "N1QAE",
              "N1WR",
              "N2BJ",
              "N2DVQ",
              "N2FF",
              "N2HTT",
              "N2IC",
              "N2JDQ",
              "N2MM",
              "N2NT",
              "N2RD",
              "N2SI",
              "N2TM",
              "N2UT",
              "N2WQ",
              "N3AD",
              "N3ALN",
              "N3BB",
              "N3DXX",
              "N3KS",
              "N3MK",
              "N3OC",
              "N3PPH",
              "N3QQ",
              "N3RC",
              "N3RR",
              "N3RS",
              "N3VBN",
              "N3WNX",
              "N3XLS",
              "N3XX",
              "N4AF",
              "N4BP",
              "N4CE",
              "N4DA",
              "N4DAG",
              "N4DW",
              "N4FX",
              "N4GI",
              "N4JIK",
              "N4LV",
              "N4NUI",
              "N4NW",
              "N4OC",
              "N4OGW",
              "N4PHT",
              "N4PN",
              "N4ST",
              "N4UA",
              "N4UPX",
              "N4URW",
              "N4UU",
              "N4WZ",
              "N4XL",
              "N4ZR",
              "N4ZZ",
              "N5AU",
              "N5BF",
              "N5BL",
              "N5DO",
              "N5DX",
              "N5FO",
              "N5HYP",
              "N5JB",
              "N5KDZ",
              "N5KO",
              "N5LNL",
              "N5LYJ",
              "N5MOA",
              "N5MV",
              "N5OYA",
              "N5QQ",
              "N5RKD",
              "N5RN",
              "N5RZ",
              "N5UL",
              "N5UM",
              "N5UWY",
              "N5WLA",
              "N5WR",
              "N5XE",
              "N5XZ",
              "N5YA",
              "N5ZGT",
              "N5ZK",
              "N5ZO",
              "N6AN",
              "N6BM",
              "N6BV",
              "N6CK",
              "N6CVA",
              "N6CY",
              "N6DB",
              "N6DE",
              "N6HC",
              "N6IE",
              "N6JW",
              "N6KL",
              "N6MA",
              "N6MEF",
              "N6ML",
              "N6NF",
              "N6PFX",
              "N6PN",
              "N6RO",
              "N6SMU",
              "N6TU",
              "N6TV",
              "N6WBL",
              "N6WM",
              "N6XG",
              "N6XI",
              "N6ZFO",
              "N7AXW",
              "N7BPA",
              "N7BT",
              "N7IV",
              "N7JFP",
              "N7KA",
              "N7LMV",
              "N7LOX",
              "N7MQ",
              "N7MZW",
              "N7ON",
              "N7PGA",
              "N7QMT",
              "N7QR",
              "N7RBP",
              "N7RQ",
              "N7TR",
              "N7TT",
              "N7VM",
              "N7VS",
              "N7W",
              "N7WA",
              "N7WEJ",
              "N7XU",
              "N7YK",
              "N7ZN",
              "N8AA",
              "N8BB",
              "N8EA",
              "N8GU",
              "N8HR",
              "N8II",
              "N8OO",
              "N8RY",
              "N8SNM",
              "N8TR",
              "N8YOH",
              "N9AKR",
              "N9CK",
              "N9CO",
              "N9CVB",
              "N9GF",
              "N9GUE",
              "N9HH",
              "N9KK",
              "N9KO",
              "N9LAH",
              "N9NC",
              "N9NTC",
              "N9RV",
              "N9TGR",
              "N9UY",
              "N9WKW",
              "NA4BW",
              "NA5AA",
              "NA5TR",
              "NA6E",
              "NB1U",
              "NB2T",
              "NB7V",
              "NC0B",
              "NC1I",
              "ND0C",
              "ND2T",
              "ND3D",
              "ND3H",
              "NE0U",
              "NE1C",
              "NE9U",
              "NF6A",
              "NF6P",
              "NF9V",
              "NG6S",
              "NG7Z",
              "NH6JC",
              "NH6P",
              "NH7A",
              "NH7O",
              "NH8S",
              "NI6T",
              "NI7F",
              "NJ7N",
              "NK7J",
              "NK7U",
              "NL7V",
              "NN1N",
              "NN3W",
              "NN4FL",
              "NN5J",
              "NN5Z",
              "NN6EE",
              "NN7ZZ",
              "NO3M",
              "NO4Y",
              "NO6X",
              "NO8R",
              "NP2I",
              "NP2X",
              "NQ4U",
              "NR5M",
              "NR5O",
              "NR6S",
              "NS2C",
              "NS2R",
              "NS2X",
              "NS4X",
              "NT2A",
              "NT6X",
              "NU1AW",
              "NU1AW",
              "NU1O",
              "NU6S",
              "NU6T",
              "NV0P",
              "NV4B",
              "NW2K",
              "NW3R",
              "NW4V",
              "NW5Y",
              "NW6H",
              "NW8U",
              "NX0X",
              "NX1P",
              "NX5M",
              "NX5O",
              "NX6T",
              "NY3A",
              "NY7U",
              "NZ8V",
              "OH8L",
              "OH8X",
              "OK1NZJ",
              "OK2PDM",
              "OL1C",
              "OM2VL",
              "OM3BH",
              "OM7M",
              "OQ5M",
              "OT5A",
              "P40F",
              "P40L",
              "P40N",
              "P40V",
              "PA0JHS",
              "PA3ACA",
              "PJ2",
              "PJ2T",
              "PJ4A",
              "PJ4G",
              "PJ4X",
              "PR5B",
              "PS2T",
              "PT5T",
              "PW7T",
              "PX5E",
              "PY2NY",
              "PY9FP",
              "R2DD",
              "RA0CGY",
              "RA0FLP",
              "RG3R",
              "RK3BF",
              "RL3BM",
              "RV3IC",
              "RV6ALI",
              "RV6FT",
              "S53EO",
              "SJ2W",
              "SK3W",
              "SN2K",
              "SO9Q",
              "SP3CUG",
              "SV2GNC",
              "T32C",
              "TD6E",
              "TF3CW",
              "TI8M",
              "TM0HQ",
              "TM0T",
              "TM2B",
              "TM4Q",
              "TM6M",
              "TO5A",
              "TX7M",
              "UA0DC",
              "UA0FM",
              "UA0FO",
              "UA0IT",
              "UA0ZK",
              "UA3ICN",
              "UA9HR",
              "UA9PC",
              "UN7DA",
              "UN8GV",
              "UR3CTB",
              "UT5ID",
              "UT7QF",
              "UT7UW",
              "UU9JQ",
              "UW5ZM",
              "UY9IO",
              "V26M",
              "V31TP",
              "V48M",
              "VA1CHP",
              "VA2EW",
              "VA2III",
              "VA2RAC",
              "VA3DX",
              "VA3PL",
              "VA3WLD",
              "VA3YOJ",
              "VA3YP",
              "VA4DB",
              "VA5AA",
              "VA5LF",
              "VA6AFS",
              "VA6AM",
              "VA7AM",
              "VA7FC",
              "VA7GEM",
              "VA7HU",
              "VA7IR",
              "VA7PX",
              "VA7RME",
              "VA7RN",
              "VA7RR",
              "VA7ST",
              "VA7WS",
              "VA7XX",
              "VC3O",
              "VE1CHW",
              "VE1DX",
              "VE1ZA",
              "VE2SG",
              "VE3CX",
              "VE3CXD",
              "VE3DZ",
              "VE3EJ",
              "VE3EQV",
              "VE3FMC",
              "VE3KAO",
              "VE3KZ",
              "VE3KZL",
              "VE3MCF",
              "VE3MIS",
              "VE3NLS",
              "VE3NOO",
              "VE3OI",
              "VE3QO",
              "VE3RZ",
              "VE3TA",
              "VE3TU",
              "VE3UTT",
              "VE3XN",
              "VE3ZUP",
              "VE4EAR",
              "VE4MG",
              "VE4YU",
              "VE5AAD",
              "VE5MX",
              "VE5PV",
              "VE5SF",
              "VE5UO",
              "VE5ZX",
              "VE6A0",
              "VE6AO",
              "VE6EPK",
              "VE6EX",
              "VE6FI",
              "VE6GCE",
              "VE6RAC",
              "VE6SQ",
              "VE6TL",
              "VE6WQ",
              "VE6WTF",
              "VE7BC",
              "VE7BSM",
              "VE7CC",
              "VE7CF",
              "VE7DB",
              "VE7DQA",
              "VE7HBS",
              "VE7IG",
              "VE7IO",
              "VE7NBQ",
              "VE7NSR",
              "VE7OGO",
              "VE7OM",
              "VE7QJ",
              "VE7RSV",
              "VE7VI",
              "VE7WO",
              "VE7XF",
              "VE7YU",
              "VE7ZZF",
              "VE8EV",
              "VE8PR",
              "VE9AA",
              "VG7G",
              "VK2XN",
              "VK3BM",
              "VK4BDJ",
              "VK4CMV",
              "VK4NM",
              "VP2EC",
              "VP5H",
              "VR2YYW",
              "VX3OI",
              "VX6AO",
              "VY1EI",
              "VY2TT",
              "VY2ZM",
              "W0AW",
              "W0BH",
              "W0CEM",
              "W0CHH",
              "W0DHB",
              "W0DLE",
              "W0EM",
              "W0ETT",
              "W0EWD",
              "W0GM",
              "W0HJW",
              "W0IW",
              "W0LPD",
              "W0LSD",
              "W0MRM",
              "W0NA",
              "W0NBP",
              "W0NO",
              "W0NTA",
              "W0ODZ",
              "W0PSK",
              "W0QL",
              "W0QU",
              "W0SD",
              "W0TUP",
              "W0UA",
              "W0WP",
              "W0YJT",
              "W0YK",
              "W0YV",
              "W0ZA",
              "W0ZP",
              "W0ZQ",
              "W1AQ",
              "W1AW",
              "W1AW",
              "W1AW",
              "W1CAM",
              "W1CTN",
              "W1ESE",
              "W1NG",
              "W1OP",
              "W1PID",
              "W1PL",
              "W1RH",
              "W1RPG",
              "W1SJ",
              "W1SRD",
              "W1TR",
              "W1UE",
              "W1UJ",
              "W1VE",
              "W1WEF",
              "W1XE",
              "W1XT",
              "W1XX",
              "W1YK",
              "W1YQ",
              "W1ZT",
              "W2AN",
              "W2BC",
              "W2BEE",
              "W2DLL",
              "W2EG",
              "W2FU",
              "W2ID",
              "W2PV",
              "W2RE",
              "W2VJN",
              "W2VKT",
              "W2W",
              "W2YC",
              "W3BW",
              "W3DPW",
              "W3DQ",
              "W3IDT",
              "W3IUU",
              "W3KL",
              "W3MLK",
              "W3NX",
              "W3PP",
              "W3RC",
              "W3TZ",
              "W3ZZ",
              "W4AAA",
              "W4AN",
              "W4BQF",
              "W4DJW",
              "W4E",
              "W4EEH",
              "W4EF",
              "W4EJY",
              "W4GAC",
              "W4GDG",
              "W4HZ",
              "W4IFI",
              "W4ML",
              "W4MPS",
              "W4MR",
              "W4MYA",
              "W4NF",
              "W4NZ",
              "W4PHS",
              "W4PM",
              "W4RM",
              "W4SVO",
              "W4UAL",
              "W4UAT",
              "W4UK",
              "W4VX",
              "W4ZEK",
              "W4ZW",
              "W5ADD",
              "W5AP",
              "W5ASP",
              "W5EX",
              "W5GHZ",
              "W5ISP",
              "W5JJ",
              "W5JK",
              "W5KFT",
              "W5KI",
              "W5MX",
              "W5PDW",
              "W5RQ",
              "W5RTA",
              "W5RU",
              "W5UE",
              "W5WMU",
              "W5WW",
              "W5WZ",
              "W5XD",
              "W6AEA",
              "W6AFA",
              "W6BX",
              "W6DAW",
              "W6DPD",
              "W6EU",
              "W6FB",
              "W6FUV",
              "W6GZG",
              "W6H",
              "W6K",
              "W6KY",
              "W6NL",
              "W6NV",
              "W6NWG",
              "W6OAT",
              "W6ONV",
              "W6OQI",
              "W6P",
              "W6PH",
              "W6PK",
              "W6RFU",
              "W6RGG",
              "W6RKC",
              "W6SX",
              "W6T",
              "W6TA",
              "W6TAI",
              "W6TK",
              "W6UB",
              "W6USN",
              "W6VAR",
              "W6WRT",
              "W6XR",
              "W6XU",
              "W6YI",
              "W6YX",
              "W7CT",
              "W7DAX",
              "W7DGZ",
              "W7DTG",
              "W7GKF",
              "W7IJ",
              "W7IV",
              "W7JBM",
              "W7JY",
              "W7MEW",
              "W7MMI",
              "W7NBH",
              "W7OM",
              "W7PU",
              "W7RM",
              "W7RN",
              "W7RY",
              "W7S",
              "W7SAA",
              "W7SW",
              "W7TVC",
              "W7TYN",
              "W7VJ",
              "W7WA",
              "W7WHY",
              "W7WMO",
              "W7WW",
              "W7YAQ",
              "W7YES",
              "W7YVK",
              "W7ZR",
              "W7ZRC",
              "W8DM",
              "W8EDU",
              "W8FJ",
              "W8FN",
              "W8GAZ",
              "W8GG",
              "W8JI",
              "W8JWN",
              "W8MJ",
              "W8OU",
              "W8PEN",
              "W8QT",
              "W8TJK",
              "W8TRX",
              "W8TTY",
              "W8ZR",
              "W9COX",
              "W9CRB",
              "W9ELI",
              "W9FZ",
              "W9GIR",
              "W9IMS",
              "W9IU",
              "W9PN",
              "W9RE",
              "W9RTB",
              "W9SN",
              "W9YX",
              "WA0EIR",
              "WA0KDS",
              "WA0LJM",
              "WA0ULX",
              "WA1ESO",
              "WA1FCN",
              "WA2BCK",
              "WA2JWL",
              "WA2KHP",
              "WA3A",
              "WA3EKL",
              "WA3LCO",
              "WA3QHJ",
              "WA4MAE",
              "WA4STO",
              "WA4WTG",
              "WA5AR",
              "WA5DJJ",
              "WA5MS",
              "WA5TLP",
              "WA5TYJ",
              "WA5ZUP",
              "WA6FGV",
              "WA6GBW",
              "WA6KHK",
              "WA6O",
              "WA6OVP",
              "WA6PXX",
              "WA6SEU",
              "WA6SR",
              "WA6ZTY",
              "WA7DUH",
              "WA7HYD",
              "WA7IPM",
              "WA7LNW",
              "WA7LT",
              "WA7NB",
              "WA7SCH",
              "WA7U",
              "WA7YAZ",
              "WA8FRE",
              "WA8ZBT",
              "WA9IVH",
              "WA9JBR",
              "WB0GBI",
              "WB0PTO",
              "WB0SOK",
              "WB0TEV",
              "WB1ABQ",
              "WB1GQR",
              "WB2REM",
              "WB2SXY",
              "WB3FIZ",
              "WB4MSG",
              "WB4ZIQ",
              "WB5AAA",
              "WB5STU",
              "WB5TLA",
              "WB5YBZ",
              "WB6JJJ",
              "WB6L",
              "WB6ORZ",
              "WB6RER",
              "WB6WTM",
              "WB7SEC",
              "WB7WNF",
              "WC2W",
              "WC6H",
              "WD0EBZ",
              "WD0EDO",
              "WD0T",
              "WD4IXD",
              "WD4LBR",
              "WD5K",
              "WD6CIM",
              "WD6CWE",
              "WD8S",
              "WE4S",
              "WE6Z",
              "WE9V",
              "WF0GMN",
              "WF4W",
              "WG7GW",
              "WG7Q",
              "WG7Y",
              "WH6R",
              "WH7M",
              "WH7Z",
              "WI7N",
              "WK0P",
              "WK4P",
              "WL7BDO",
              "WM2Z",
              "WM5R",
              "WN2T",
              "WN6K",
              "WO8CC",
              "WO8J",
              "WQ2N",
              "WR3Z",
              "WS6K",
              "WS7G",
              "WS7I",
              "WS7V",
              "WT6X",
              "WT9Q",
              "WT9U",
              "WV4Y",
              "WV6I",
              "WW0AL",
              "WW0WWW",
              "WW4LL",
              "WW9R",
              "WX0B",
              "WX0GLD",
              "WX0U",
              "WX3B",
              "WX6V",
              "WX7P",
              "WY4Y",
              "WY6VW",
              "WY7FD",
              "WY7SS",
              "WY8I",
              "WZ8P",
              "XE1GK",
              "XE2B",
              "XE2HWJ",
              "XE2IW",
              "XE2K",
              "XE2S",
              "XE2SMP",
              "XE2URF",
              "XE3DX",
              "XL3A",
              "YB8EXL",
              "YC8HI",
              "YV5AM",
              "YW4D",
              "ZD8Z",
              "ZF1A",
              "ZL1BD",
              "ZL1BIV",
              "ZL2VF",
              "ZL3GA",
              "ZL3HAM",
              "ZL3IO",
              "ZL3NB",
              "ZL8X",
              "ZS2ACP",
              "ZS2GK",
              "ZW5B",
              "ZY7C"]

db = Mysql.new("localhost", "dbtest", "dbtest", 'CQPACE_test')
db.query("delete from OPERATOR")
db.query("delete from QSO")
db.query("delete from LOG")
res = db.query("select ID from QSO_STATUS where NAME='OK' LIMIT 1")
if res.nil? or res.num_rows == 0
  db.query("insert into QSO_STATUS (NAME) value ('OK')")
end

rng = Random.new

def randomLocation(db)
  rows = db.query("select NAME, TYPE from MULTIPLIER where NAME <> 'CA' order by RAND() LIMIT 1")
  results = rows.fetch_row
  return results[0], results[1]
end

def randomOpCategory(rng)
  rnd = rng.rand(100)
  if (rnd >= 98)
    return "CHECK"
  elsif (rnd >= 92)
    return "MULTI-MULTI"
  elsif (rnd >= 87)
    return "MULTI-SINGLE"
  end
  return "SINGLE-OP"
end

def randomCategory(db, cat)
  rows = db.query("select NAME from " + cat + "_CATEGORY order by RAND() LIMIT 1");
  results = rows.fetch_row
  return results[0]
end

def insertExtraOps(db, rng, availcalls, numops, callsign)
  id = (db.query("select last_insert_id()").fetch_row[0]).to_i
  numops.times {
    ind = rng.rand(availcalls.length)
    db.query("insert into OPERATOR (CALLSIGN, LOG_ID) values (\"" + availcalls[ind] +
             "\", " + id.to_s + ")");
    availcalls.delete_at(ind)
  }
  if ((numops == 0) or ((numops == 2 or numops == 3) and rng.rand < 0.4))
    db.query("insert into OPERATOR (CALLSIGN, LOG_ID) values (\"" + callsign +
             "\", " + id.to_s + ")")
  end
end

def addLocation(db, callsign, location, rng, availcalls)
  opcat = randomOpCategory(rng)
  db.query("insert into LOG (CALLSIGN, CONTEST_NAME, CONTEST_YEAR, STATION_LOCATION, OPERATOR_CATEGORY, POWER_CATEGORY, STATION_CATEGORY, TRANSMITTER_CATEGORY, SUBMISSION_DATE, OVERLAY_YL, OVERLAY_YOUTH, OVERLAY_NEW_CONTESTER) values (\"" + callsign + "\", 'CA-QSO-PARTY', 2012, \"" + 
           location + "\", '" + opcat + "', '" + 
           randomCategory(db, "POWER") + "', '" + 
           randomCategory(db, "STATION") + "', '" +
           randomCategory(db, "TRANSMITTER") + "', NOW(), RAND() < 0.08, RAND() < 0.05, RAND() < 0.05)");
  if /MULTI/ =~ opcat
    insertExtraOps(db, rng, availcalls, 2+rng.rand(4), callsign)
  elsif (opcat == "SINGLE-OP" and rng.rand < 0.05)
    insertExtraOps(db, rng, availcalls, 1, callsign)
  elsif (rng.rand < 0.1)
    insertExtraOps(db, rng, availcalls, 0, callsign)
  end
end

working_copy = CALLSIGNS.uniq
used_signs = Array.new
NUMLOGS.times { 
  print working_copy.length.to_s + "\n"
  ind = rng.rand(working_copy.length)
  call = working_copy[ind]
  used_signs.push(call)
  working_copy.delete_at(ind)
  name, type = randomLocation(db)
  addLocation(db, call, name, rng, working_copy)
}

# Ensure that every multiplier has at least one log entry
result = db.query("select MULTIPLIER.NAME from MULTIPLIER left outer join LOG on MULTIPLIER.NAME = LOG.STATION_LOCATION where LOG.STATION_LOCATION is null and MULTIPLIER.NAME <> 'CA'")
result.each { |row|
  ind = rng.rand(working_copy.length)
  call = working_copy[ind]
  used_signs.push(call)
  working_copy.delete_at(ind)
  addLocation(db, call, row[0], rng)
}

def RandomContactDetails(rng)
  bands = ["160", "80", "40", "20", "15", "10", "6"]
  bandprobabilities = { "160" => 12,
    "80" => 17,
    "40" => 17,
    "20" => 17,
    "15" => 17,
    "10" => 17,
    "6" => 3}
  frequencies = { "160" => (1801..1999),
    "80" => (3501..3999),
    "40" => (7001..7299),
    "20" => (14001..14349),
    "15" => (21001..21449),
    "10" => (28001..29699),
    "6" => (50000..53999) }
  cwcutoff = {"160" => 1900, "80" => 3600, "40"=> 7125, "20" => 14150,
    "15" => 21200, "10" => 28300, "6" => 50100}
  bandrn = rng.rand(100)
  sum = 0
  band = "6"
  bands.each { |b|
    if ((bandrn >= sum) and (bandrn < (sum + bandprobabilities[b])))
      band = b
      break
    end
    sum = sum + bandprobabilities[b]
  }
  frequency = frequencies[band].begin + rng.rand(frequencies[band].end -
                                                 frequencies[band].begin);
  mode = (frequency >= cwcutoff[band] ? "PH" : "CW")
  return band, frequency, mode  
end

def CalcSerialNum(db, id)
  result = 1
  rows = db.query("select MAX(SERIAL_SENT) from QSO where LOG_ID = " +
                  id.to_s);
  rows.each { |r|
    result  = r[1].to_i + 1
  }
  return result
end

def logCall(db, rng, call1, call2)
  time = "DATE_ADD(\"2012-10-06 16:00:00\", INTERVAL " + rng.rand(1440).to_s + " MINUTE)"
  station1 = db.query("SELECT ID, STATION_LOCATION from LOG where CALLSIGN=\"" + call1 + "\" LIMIT 1").fetch_row
  station2 = db.query("SELECT ID, STATION_LOCATION from LOG where CALLSIGN=\"" + call2 + "\" LIMIT 1").fetch_row
  band, frequency, mode = RandomContactDetails(rng)
  serialnum1 = CalcSerialNum(db, station1[0])
  serialnum2 = CalcSerialNum(db, station2[0])
  db.query("insert into QSO (QSO_DATE, CALLSIGN_SENT, CALLSIGN_RECEIVED, FREQUENCY, BAND, MODE, SERIAL_SENT, SERIAL_RECEIVED, QTH_SENT, QTH_RECEIVED, LOG_ID, QSO_STATUS) values (" + 
           time  +
           ", '" + call1 + "', '" + call2 + "', " + frequency.to_s + ", '" +
           band + "', '" + mode + "', " + serialnum1.to_s + ", " + 
           serialnum2.to_s + ", '" + station1[1] + "', '" + 
           station2[1] + "', " + station1[0] + ", 'OK'), (" +
           time +
           ", '" + call2 + "', '" + call1 + "', " + frequency.to_s + ", '" +
           band + "', '" + mode + "', " + serialnum2.to_s + ", " + 
           serialnum1.to_s + ", '" + station2[1] + "', '" + 
           station1[1] + "', " + station2[0] + ", 'OK')")
end

(NUMQSOS/2).times {
  result = db.query("SELECT LOG.ID, CALLSIGN, MULTIPLIER.TYPE from LOG, MULTIPLIER where LOG.STATION_LOCATION = MULTIPLIER.NAME order by RAND() limit 1");
  row = result.fetch_row
  call1 = row[1]
  id1 = row[0]
  type1 = row[2]
  result = db.query("SELECT LOG.ID, CALLSIGN from LOG, MULTIPLIER where LOG.STATION_LOCATION = MULTIPLIER.NAME " + ((type1 == "COUNTY") ? "" : "and MULTIPLIER.TYPE = 'COUNTY'") + " and LOG.ID != " + id1.to_s + " order by RAND() limit 1")
  row = result.fetch_row
  call2 = row[1]
  id2 = row[0]
  logCall(db, rng, call1, call2)
}

# ensure each operator has at least one QSO
result = db.query("SELECT LOG.ID, CALLSIGN, MULTIPLIER.TYPE from LOG, MULTIPLIER where LOG.STATION_LOCATION = MULTIPLIER.NAME");
result.each { |row|
  call1 = row[1]
  id1 = row[0]
  type1 = row[2]
  res2 = db.query("SELECT LOG.ID, CALLSIGN from LOG, MULTIPLIER where LOG.STATION_LOCATION = MULTIPLIER.NAME " + ((type1 == "COUNTY") ? "" : "and MULTIPLIER.TYPE = 'COUNTY'") + " and LOG.ID != " + id1.to_s + " order by RAND() limit 1")
  row2 = res2.fetch_row
  call2 = row2[1]
  id2 = row2[0]
  logCall(db, rng, call1, call2)
}

# ensure that a few CA stations worked all states and provinces
result = db.query("SELECT LOG.ID, CALLSIGN from LOG, MULTIPLIER where LOG.STATION_LOCATION = MULTIPLIER.NAME and MULTIPLIER.TYPE = 'COUNTY' order by RAND() limit " + NUMALLMULTS.to_s)
result.each { |row|
  missing = db.query("SELECT MULTIPLIER.NAME from MULTIPLIER where (MULTIPLIER.TYPE = 'STATE' or MULTIPLIER.TYPE = 'PROVINCE') AND NAME <> 'CA'")
  missing.each { |noqso|
    newqso = db.query("SELECT ID, CALLSIGN from LOG where LOG.STATION_LOCATION = '" +
                      noqso[0] + "' and ID != " + row[0] + 
                      " order by RAND() limit 1")
    logCall(db, rng, row[1], newqso.fetch_row[1])
  }
}



# ensure that a few non-CA stations worked all counties
result = db.query("SELECT LOG.ID, CALLSIGN from LOG, MULTIPLIER where LOG.STATION_LOCATION = MULTIPLIER.NAME and MULTIPLIER.TYPE != 'COUNTY' order by RAND() limit " + NUMALLMULTS.to_s)
result.each { |row|
  missing = db.query("SELECT MULTIPLIER.NAME from MULTIPLIER where MULTIPLIER.TYPE = 'COUNTY'")
  missing.each { |noqso|
    newqso = db.query("SELECT ID, CALLSIGN from LOG where LOG.STATION_LOCATION = '" +
                      noqso[0] + "' and ID != " + row[0] + 
                      " order by RAND() limit 1")
    logCall(db, rng, row[1], newqso.fetch_row[1])
  }
}
