SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

ALTER TABLE `CQPACE`.`LOG` DROP FOREIGN KEY `FK_LOG_CLUB_ALIAS` ;

ALTER TABLE `CQPACE`.`MULTIPLIER_ALIAS` DROP FOREIGN KEY `FK_MULTIPLIER_ID` ;

ALTER TABLE `CQPACE`.`LOG` 
  ADD CONSTRAINT `FK_LOG_CLUB`
  FOREIGN KEY (`CLUB` )
  REFERENCES `CQPACE`.`CLUB` (`NAME` )
  ON DELETE NO ACTION
  ON UPDATE NO ACTION
, ADD INDEX `FK_LOG_CLUB_idx` (`CLUB` ASC) 
, DROP INDEX `FK_LOG_CLUB_ALIAS_idx` ;

ALTER TABLE `CQPACE`.`QSO` 
DROP INDEX `FK_QSO_LOG` ;

ALTER TABLE `CQPACE`.`MULTIPLIER_ALIAS` CHANGE COLUMN `MULTIPLIER_NAME` `MULTIPLIER_NAME` VARCHAR(4) NOT NULL  , CHANGE COLUMN `MULTIPLIER_ID` `MULTIPLIER_ID` INT(11) NOT NULL  , 
  ADD CONSTRAINT `FK_MULTIPLIER_ID`
  FOREIGN KEY (`MULTIPLIER_ID` )
  REFERENCES `CQPACE`.`MULTIPLIER` (`ID` )
  ON DELETE NO ACTION
  ON UPDATE NO ACTION, 
  ADD CONSTRAINT `FK_MULTIPLIER_ALIAS_MULTIPLIER_NAME`
  FOREIGN KEY (`MULTIPLIER_NAME` )
  REFERENCES `CQPACE`.`MULTIPLIER` (`NAME` )
  ON DELETE NO ACTION
  ON UPDATE NO ACTION
, ADD INDEX `FK_MULTIPLIER_ALIAS_MULTIPLIER_NAME_idx` (`MULTIPLIER_NAME` ASC) ;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
