insert into CLUB_ALIAS
  set
  CLUB_NAME = 'DOGGIE OP G',
  ALIAS = 'DOGGIE OP G',
  CLUB_ID = (select ID from CLUB where NAME = 'DOGGIE OP G');
insert into CLUB_ALIAS
  set
  CLUB_NAME = 'SOUTHEAST CONTEST CLUB',
  ALIAS = 'SOUTHEAST CONTEST CLUB',
  CLUB_ID = (select ID from CLUB where NAME = 'SOUTHEAST CONTEST CLUB');
insert into CLUB_ALIAS
  set
  CLUB_NAME = 'BRITISH COLUMBIA DX CLUB',
  ALIAS = 'BRITISH COLUMBIA DX CLUB',
  CLUB_ID = (select ID from CLUB where NAME = 'BRITISH COLUMBIA DX CLUB');
insert into CLUB_ALIAS
  set
  CLUB_NAME = 'STANFORD AMATEUR RADIO CLUB',
  ALIAS = 'STANFORD AMATEUR RADIO CLUB',
  CLUB_ID = (select ID from CLUB where NAME = 'STANFORD AMATEUR RADIO CLUB');
insert into CLUB_ALIAS
  set
  CLUB_NAME = 'UNITED RADIO AMATEUR CLUB, INC.',
  ALIAS = 'UNITED RADIO AMATEUR CLU',
  CLUB_ID = (select ID from CLUB where NAME = 'UNITED RADIO AMATEUR CLUB, INC.');
insert into CLUB_ALIAS
  set
  CLUB_NAME = 'ORDER OF BOILED OWLS OF NEW YORK',
  ALIAS = 'ORDER OF BOILED OWLS OF NEW YORK',
  CLUB_ID = (select ID from CLUB where NAME = 'ORDER OF BOILED OWLS OF NEW YORK');
insert into CLUB_ALIAS
  set
  CLUB_NAME = 'CRC',
  ALIAS = 'CRC',
  CLUB_ID = (select ID from CLUB where NAME = 'CRC');
insert into CLUB_ALIAS
  set
  CLUB_NAME = 'SOUTHERN CALIFORNIA CONTEST CLUB',
  ALIAS = 'SOUTHERN CALIFORNIA CONTEST CLUB',
  CLUB_ID = (select ID from CLUB where NAME = 'SOUTHERN CALIFORNIA CONTEST CLUB');
insert into CLUB_ALIAS
  set
  CLUB_NAME = 'WEST JERSEY DX CLUB',
  ALIAS = 'WEST JERSEY DX CLUB',
  CLUB_ID = (select ID from CLUB where NAME = 'WEST JERSEY DX CLUB');
insert into CLUB_ALIAS
  set
  CLUB_NAME = 'NACHO',
  ALIAS = 'NACHO',
  CLUB_ID = (select ID from CLUB where NAME = 'NACHO');
insert into CLUB_ALIAS
  set
  CLUB_NAME = 'TWIN CITY HAM CLUB',
  ALIAS = 'TWIN CITY HAM CLUB',
  CLUB_ID = (select ID from CLUB where NAME = 'TWIN CITY HAM CLUB');
insert into CLUB_ALIAS
  set
  CLUB_NAME = 'BOULDER ARC',
  ALIAS = 'BOULDER ARC',
  CLUB_ID = (select ID from CLUB where NAME = 'BOULDER ARC');
insert into CLUB_ALIAS
  set
  CLUB_NAME = 'SOUTHWEST OHIO DX ASSN',
  ALIAS = 'SOUTHWEST OHIO DX ASSN',
  CLUB_ID = (select ID from CLUB where NAME = 'SOUTHWEST OHIO DX ASSN');
insert into CLUB_ALIAS
  set
  CLUB_NAME = 'NORTH TEXAS MICROWAVE SOCIETY',
  ALIAS = 'NORTH TEXAS MICROWAVE SOCIETY',
  CLUB_ID = (select ID from CLUB where NAME = 'NORTH TEXAS MICROWAVE SOCIETY');
insert into CLUB_ALIAS
  set
  CLUB_NAME = 'YANKEE CLIPPER CONTEST CLUB',
  ALIAS = 'YCCC',
  CLUB_ID = (select ID from CLUB where NAME = 'YANKEE CLIPPER CONTEST CLUB');
insert into CLUB_ALIAS
  set
  CLUB_NAME = 'SOCIETY OF MIDWEST CONTESTERS',
  ALIAS = 'SOCIETY OF MIDWEST CONTESTERS',
  CLUB_ID = (select ID from CLUB where NAME = 'SOCIETY OF MIDWEST CONTESTERS');
insert into CLUB_ALIAS
  set
  CLUB_NAME = 'NORTHERN CALIFORNIA CONTEST CLUB',
  ALIAS = 'NORTHERN CALIFORNIA CONTEST CLUB',
  CLUB_ID = (select ID from CLUB where NAME = 'NORTHERN CALIFORNIA CONTEST CLUB');
insert into CLUB_ALIAS
  set
  CLUB_NAME = 'SOUTHERN CALIFORNIA CONTEST CLUB',
  ALIAS = 'SCCC',
  CLUB_ID = (select ID from CLUB where NAME = 'SOUTHERN CALIFORNIA CONTEST CLUB');
insert into CLUB_ALIAS
  set
  CLUB_NAME = 'ALABAMA CONTEST GROUP',
  ALIAS = 'ALABAMA CONTEST GROUP',
  CLUB_ID = (select ID from CLUB where NAME = 'ALABAMA CONTEST GROUP');
insert into CLUB_ALIAS
  set
  CLUB_NAME = 'MOTHER LODE DX AND CONTEST CLUB',
  ALIAS = 'MOTHERLODE DX AND CONTEST CLUB (MLDXCC)',
  CLUB_ID = (select ID from CLUB where NAME = 'MOTHER LODE DX AND CONTEST CLUB');
insert into CLUB_ALIAS
  set
  CLUB_NAME = 'RAE',
  ALIAS = 'RAE',
  CLUB_ID = (select ID from CLUB where NAME = 'RAE');
insert into CLUB_ALIAS
  set
  CLUB_NAME = 'ALBERTA CLIPPERS',
  ALIAS = 'ALBERTA CLIPPERS',
  CLUB_ID = (select ID from CLUB where NAME = 'ALBERTA CLIPPERS');
insert into CLUB_ALIAS
  set
  CLUB_NAME = 'WESTERN NY CONTEST CLUB',
  ALIAS = 'WESTERN NY CONTEST CLUB',
  CLUB_ID = (select ID from CLUB where NAME = 'WESTERN NY CONTEST CLUB');
insert into CLUB_ALIAS
  set
  CLUB_NAME = 'MOTHER LODE DX AND CONTEST CLUB',
  ALIAS = 'MOTHERLODE DX/CONTEST CLUB',
  CLUB_ID = (select ID from CLUB where NAME = 'MOTHER LODE DX AND CONTEST CLUB');
insert into CLUB_ALIAS
  set
  CLUB_NAME = 'MOTHER LODE DX AND CONTEST CLUB',
  ALIAS = 'MOTHER LODE DX/CONTEST CLUB',
  CLUB_ID = (select ID from CLUB where NAME = 'MOTHER LODE DX AND CONTEST CLUB');
insert into CLUB_ALIAS
  set
  CLUB_NAME = 'MAD RIVER RADIO CLUB',
  ALIAS = 'MAD RIVER RADIO CLUB',
  CLUB_ID = (select ID from CLUB where NAME = 'MAD RIVER RADIO CLUB');
insert into CLUB_ALIAS
  set
  CLUB_NAME = 'CONTEST CLUB ONTARIO',
  ALIAS = 'CONTEST CLUB ONTARIO',
  CLUB_ID = (select ID from CLUB where NAME = 'CONTEST CLUB ONTARIO');
insert into CLUB_ALIAS
  set
  CLUB_NAME = 'POTOMAC VALLEY RADIO CLUB',
  ALIAS = 'POTOMAC VALLEY RADIO CLUB',
  CLUB_ID = (select ID from CLUB where NAME = 'POTOMAC VALLEY RADIO CLUB');
insert into CLUB_ALIAS
  set
  CLUB_NAME = 'URE',
  ALIAS = 'URE',
  CLUB_ID = (select ID from CLUB where NAME = 'URE');
insert into CLUB_ALIAS
  set
  CLUB_NAME = 'NONE SPECIFIED',
  ALIAS = 'WEST VALLEY ARA',
  CLUB_ID = (select ID from CLUB where NAME = 'NONE SPECIFIED');
insert into CLUB_ALIAS
  set
  CLUB_NAME = 'MINNESOTA WIRELESS ASSOCIATION',
  ALIAS = 'MN WIRELESS ASSN',
  CLUB_ID = (select ID from CLUB where NAME = 'MINNESOTA WIRELESS ASSOCIATION');
insert into CLUB_ALIAS
  set
  CLUB_NAME = 'SCCARC',
  ALIAS = 'SCCARC',
  CLUB_ID = (select ID from CLUB where NAME = 'SCCARC');
insert into CLUB_ALIAS
  set
  CLUB_NAME = 'CENTRAL OR DX CLUB',
  ALIAS = 'CENTRAL OR DX CLUB',
  CLUB_ID = (select ID from CLUB where NAME = 'CENTRAL OR DX CLUB');
insert into CLUB_ALIAS
  set
  CLUB_NAME = 'GRAND MESA CONTESTERS OF COLORADO',
  ALIAS = 'GRAND MESA CONTESTERS OF COLORADO',
  CLUB_ID = (select ID from CLUB where NAME = 'GRAND MESA CONTESTERS OF COLORADO');
insert into CLUB_ALIAS
  set
  CLUB_NAME = 'REDWOOD EMPIRE DX ASSOCIATION',
  ALIAS = 'REDWOOD EMPIRE DX ASN',
  CLUB_ID = (select ID from CLUB where NAME = 'REDWOOD EMPIRE DX ASSOCIATION');
insert into CLUB_ALIAS
  set
  CLUB_NAME = 'MONTEREY BAY AMATEUR RADIO ASSOCIATION',
  ALIAS = 'MBARA (MONTEREY BAY ARA)',
  CLUB_ID = (select ID from CLUB where NAME = 'MONTEREY BAY AMATEUR RADIO ASSOCIATION');
insert into CLUB_ALIAS
  set
  CLUB_NAME = 'NORTH HILLS AMATEUR RADIO CONTEST SOCIETY',
  ALIAS = 'NORTH HILLS AMATEUR RADIO CONTEST SOCIETY',
  CLUB_ID = (select ID from CLUB where NAME = 'NORTH HILLS AMATEUR RADIO CONTEST SOCIETY');
insert into CLUB_ALIAS
  set
  CLUB_NAME = 'ARCECS',
  ALIAS = 'ARCECS',
  CLUB_ID = (select ID from CLUB where NAME = 'ARCECS');
insert into CLUB_ALIAS
  set
  CLUB_NAME = 'SOUTHERN MARIN AMATEUR RADIO TRANS. SOCIETY',
  ALIAS = 'SOUTHERN MARIN AMATEUR RADIO TRANS. SOCIETY',
  CLUB_ID = (select ID from CLUB where NAME = 'SOUTHERN MARIN AMATEUR RADIO TRANS. SOCIETY');
insert into CLUB_ALIAS
  set
  CLUB_NAME = 'SOCIETY OF MIDWEST CONTESTERS',
  ALIAS = 'SMC',
  CLUB_ID = (select ID from CLUB where NAME = 'SOCIETY OF MIDWEST CONTESTERS');
insert into CLUB_ALIAS
  set
  CLUB_NAME = 'FLORIDA CONTEST GROUP',
  ALIAS = 'FLORIDA CONTEST GROUP',
  CLUB_ID = (select ID from CLUB where NAME = 'FLORIDA CONTEST GROUP');
insert into CLUB_ALIAS
  set
  CLUB_NAME = 'ESCONDIDO AMATEUR RADIO SOCIETY',
  ALIAS = 'ESCONDIDO AMATEUR RADIO SOCIETY',
  CLUB_ID = (select ID from CLUB where NAME = 'ESCONDIDO AMATEUR RADIO SOCIETY');
insert into CLUB_ALIAS
  set
  CLUB_NAME = 'SOCIETY OF MIDWEST CONTESTERS',
  ALIAS = 'SOCIETY OF MIDWEST CONTESTERS',
  CLUB_ID = (select ID from CLUB where NAME = 'SOCIETY OF MIDWEST CONTESTERS');
insert into CLUB_ALIAS
  set
  CLUB_NAME = 'TUPY DX GROUP',
  ALIAS = 'TUPY DX GROUP',
  CLUB_ID = (select ID from CLUB where NAME = 'TUPY DX GROUP');
insert into CLUB_ALIAS
  set
  CLUB_NAME = 'UNITED RADIO AMATEUR CLUB, INC.',
  ALIAS = 'UNITED RADIO AMATEUR CLUB, INC.',
  CLUB_ID = (select ID from CLUB where NAME = 'UNITED RADIO AMATEUR CLUB, INC.');
insert into CLUB_ALIAS
  set
  CLUB_NAME = 'TENNESSEE CONTEST GROUP',
  ALIAS = 'TENNESSEE CONTEST GROUP',
  CLUB_ID = (select ID from CLUB where NAME = 'TENNESSEE CONTEST GROUP');
insert into CLUB_ALIAS
  set
  CLUB_NAME = 'HUDSON VALLEY CONTESTERS AND DXERS',
  ALIAS = 'HUDSON VALLEY CONTESTERS AND DXERS',
  CLUB_ID = (select ID from CLUB where NAME = 'HUDSON VALLEY CONTESTERS AND DXERS');
insert into CLUB_ALIAS
  set
  CLUB_NAME = 'FRANKFORD RADIO CLUB',
  ALIAS = 'FRC',
  CLUB_ID = (select ID from CLUB where NAME = 'FRANKFORD RADIO CLUB');
insert into CLUB_ALIAS
  set
  CLUB_NAME = 'NEVADA COUNTRY AMATEUR RADIO CLUB',
  ALIAS = 'NEVADA COUNTRY AMATEUR RADIO CLUB',
  CLUB_ID = (select ID from CLUB where NAME = 'NEVADA COUNTRY AMATEUR RADIO CLUB');
insert into CLUB_ALIAS
  set
  CLUB_NAME = 'SOUTHERN CALIFORNIA CONTEST CLUB',
  ALIAS = 'SOUTHERN CALIFORNIA CONTEST CLUB',
  CLUB_ID = (select ID from CLUB where NAME = 'SOUTHERN CALIFORNIA CONTEST CLUB');
insert into CLUB_ALIAS
  set
  CLUB_NAME = 'FLORIDA CONTEST GROUP',
  ALIAS = 'FLORIDA CONTEST GROUP',
  CLUB_ID = (select ID from CLUB where NAME = 'FLORIDA CONTEST GROUP');
insert into CLUB_ALIAS
  set
  CLUB_NAME = 'FOSSIL FALLS PEANUT WHISTLES',
  ALIAS = 'FOSSIL FALLS PEANUT WHISTLES',
  CLUB_ID = (select ID from CLUB where NAME = 'FOSSIL FALLS PEANUT WHISTLES');
insert into CLUB_ALIAS
  set
  CLUB_NAME = 'WYDXCC',
  ALIAS = 'WYDXCC',
  CLUB_ID = (select ID from CLUB where NAME = 'WYDXCC');
insert into CLUB_ALIAS
  set
  CLUB_NAME = 'REDWOOD EMPIRE DX ASSOCIATION',
  ALIAS = 'REDWOOD EMPIRE DX ASSN.',
  CLUB_ID = (select ID from CLUB where NAME = 'REDWOOD EMPIRE DX ASSOCIATION');
insert into CLUB_ALIAS
  set
  CLUB_NAME = 'MOTHER LODE DX AND CONTEST CLUB',
  ALIAS = 'MOTHERLODE',
  CLUB_ID = (select ID from CLUB where NAME = 'MOTHER LODE DX AND CONTEST CLUB');
insert into CLUB_ALIAS
  set
  CLUB_NAME = 'SAN DIEGO DX CLUB',
  ALIAS = 'SAN DIEGO DX CLUB',
  CLUB_ID = (select ID from CLUB where NAME = 'SAN DIEGO DX CLUB');
insert into CLUB_ALIAS
  set
  CLUB_NAME = 'TENNESSEE CONTEST GROUP',
  ALIAS = 'TENNESSEE CONTEST GROUP',
  CLUB_ID = (select ID from CLUB where NAME = 'TENNESSEE CONTEST GROUP');
insert into CLUB_ALIAS
  set
  CLUB_NAME = 'SOCIETY OF MIDWEST CONTESTERS',
  ALIAS = 'SOCIETY OF MIDWESTERN CONTESTERS',
  CLUB_ID = (select ID from CLUB where NAME = 'SOCIETY OF MIDWEST CONTESTERS');
insert into CLUB_ALIAS
  set
  CLUB_NAME = 'MOTHER LODE DX AND CONTEST CLUB',
  ALIAS = 'MOTHER LODE DX AND CONTEST CLUB',
  CLUB_ID = (select ID from CLUB where NAME = 'MOTHER LODE DX AND CONTEST CLUB');
insert into CLUB_ALIAS
  set
  CLUB_NAME = 'NORTH COAST CONTESTERS',
  ALIAS = 'NORTH COAST CONTESTERS',
  CLUB_ID = (select ID from CLUB where NAME = 'NORTH COAST CONTESTERS');
insert into CLUB_ALIAS
  set
  CLUB_NAME = 'NORTHERN CALIFORNIA CONTEST CLUB',
  ALIAS = 'NORTHERN CALIFORNIA CONTEST CLUB',
  CLUB_ID = (select ID from CLUB where NAME = 'NORTHERN CALIFORNIA CONTEST CLUB');
insert into CLUB_ALIAS
  set
  CLUB_NAME = 'CALGARY AMATEUR RADIO ASSOC.',
  ALIAS = 'CALGARY AMATEUR RADIO ASSOC.',
  CLUB_ID = (select ID from CLUB where NAME = 'CALGARY AMATEUR RADIO ASSOC.');
insert into CLUB_ALIAS
  set
  CLUB_NAME = 'OKLAHOMA DX ASSN',
  ALIAS = 'OKDXA',
  CLUB_ID = (select ID from CLUB where NAME = 'OKLAHOMA DX ASSN');
insert into CLUB_ALIAS
  set
  CLUB_NAME = 'GRUPO ARGENTINO DE RADIOTELEGRAFIA (GACW)',
  ALIAS = 'GRUPO ARGENTINO DE RADIOTELEGRAFIA (GACW)',
  CLUB_ID = (select ID from CLUB where NAME = 'GRUPO ARGENTINO DE RADIOTELEGRAFIA (GACW)');
insert into CLUB_ALIAS
  set
  CLUB_NAME = 'SOUTHEAST CONTEST CLUB',
  ALIAS = 'SOUTHEAST CONTEST CLUB',
  CLUB_ID = (select ID from CLUB where NAME = 'SOUTHEAST CONTEST CLUB');
insert into CLUB_ALIAS
  set
  CLUB_NAME = 'NORTH TEXAS CONTEST CLUB',
  ALIAS = 'NORTH TEXAS CONTEST CLUB',
  CLUB_ID = (select ID from CLUB where NAME = 'NORTH TEXAS CONTEST CLUB');
insert into CLUB_ALIAS
  set
  CLUB_NAME = 'REDWOOD EMPIRE DX ASSOCIATION',
  ALIAS = 'REDXA',
  CLUB_ID = (select ID from CLUB where NAME = 'REDWOOD EMPIRE DX ASSOCIATION');
insert into CLUB_ALIAS
  set
  CLUB_NAME = 'CADXA',
  ALIAS = 'CADXA',
  CLUB_ID = (select ID from CLUB where NAME = 'CADXA');
insert into CLUB_ALIAS
  set
  CLUB_NAME = 'SOARA',
  ALIAS = 'SOARA',
  CLUB_ID = (select ID from CLUB where NAME = 'SOARA');
insert into CLUB_ALIAS
  set
  CLUB_NAME = 'MOTHER LODE DX AND CONTEST CLUB',
  ALIAS = 'MOTHER LODE DXCC',
  CLUB_ID = (select ID from CLUB where NAME = 'MOTHER LODE DX AND CONTEST CLUB');
insert into CLUB_ALIAS
  set
  CLUB_NAME = 'CENTRAL TEXAS DX AND CONTEST CLUB',
  ALIAS = 'CENTRAL TEXAS DX AND CONTEST CLUB',
  CLUB_ID = (select ID from CLUB where NAME = 'CENTRAL TEXAS DX AND CONTEST CLUB');
insert into CLUB_ALIAS
  set
  CLUB_NAME = 'CONTEST CLUB ONTARIO',
  ALIAS = 'CCO CONTEST CLUB ONTARIO',
  CLUB_ID = (select ID from CLUB where NAME = 'CONTEST CLUB ONTARIO');
insert into CLUB_ALIAS
  set
  CLUB_NAME = 'METRO DX CLUB',
  ALIAS = 'METRO DX CLUB',
  CLUB_ID = (select ID from CLUB where NAME = 'METRO DX CLUB');
insert into CLUB_ALIAS
  set
  CLUB_NAME = 'MOTHER LODE DX AND CONTEST CLUB',
  ALIAS = 'MLDXCC',
  CLUB_ID = (select ID from CLUB where NAME = 'MOTHER LODE DX AND CONTEST CLUB');
insert into CLUB_ALIAS
  set
  CLUB_NAME = 'USC AMATEUR RADIO CLUB',
  ALIAS = 'USC AMATEUR RADIO CLUB',
  CLUB_ID = (select ID from CLUB where NAME = 'USC AMATEUR RADIO CLUB');
insert into CLUB_ALIAS
  set
  CLUB_NAME = 'CONTEST CLUB ONTARIO',
  ALIAS = 'CCO',
  CLUB_ID = (select ID from CLUB where NAME = 'CONTEST CLUB ONTARIO');
insert into CLUB_ALIAS
  set
  CLUB_NAME = 'FRANKFORD RADIO CLUB',
  ALIAS = 'FRANKFORD RADIO CLUB',
  CLUB_ID = (select ID from CLUB where NAME = 'FRANKFORD RADIO CLUB');
insert into CLUB_ALIAS
  set
  CLUB_NAME = 'SOUTHERN CALIFORNIA CONTEST CLUB',
  ALIAS = 'SCCC',
  CLUB_ID = (select ID from CLUB where NAME = 'SOUTHERN CALIFORNIA CONTEST CLUB');
insert into CLUB_ALIAS
  set
  CLUB_NAME = 'MINNESOTA WIRELESS ASSOCIATION',
  ALIAS = 'MINNESOTA WIRELESS ASSOC',
  CLUB_ID = (select ID from CLUB where NAME = 'MINNESOTA WIRELESS ASSOCIATION');
insert into CLUB_ALIAS
  set
  CLUB_NAME = 'RADIOCLUB TRANSYLVANIA CONNECTION',
  ALIAS = 'RADIOCLUB TRANSYLVANIA CONNECTION',
  CLUB_ID = (select ID from CLUB where NAME = 'RADIOCLUB TRANSYLVANIA CONNECTION');
insert into CLUB_ALIAS
  set
  CLUB_NAME = 'TDXS',
  ALIAS = 'TDXS',
  CLUB_ID = (select ID from CLUB where NAME = 'TDXS');
insert into CLUB_ALIAS
  set
  CLUB_NAME = 'MOTHER LODE DX AND CONTEST CLUB',
  ALIAS = 'MOTHER LODE DX &AMP; CC',
  CLUB_ID = (select ID from CLUB where NAME = 'MOTHER LODE DX AND CONTEST CLUB');
insert into CLUB_ALIAS
  set
  CLUB_NAME = 'MOTHER LODE DX AND CONTEST CLUB',
  ALIAS = 'MOTHER LOAD DX AND CONTEST CLUB',
  CLUB_ID = (select ID from CLUB where NAME = 'MOTHER LODE DX AND CONTEST CLUB');
insert into CLUB_ALIAS
  set
  CLUB_NAME = 'MONTEREY BAY AMATEUR RADIO ASSOCIATION',
  ALIAS = 'MONTEREY BAY AMATEUR RADIO ASSN (MBARA)',
  CLUB_ID = (select ID from CLUB where NAME = 'MONTEREY BAY AMATEUR RADIO ASSOCIATION');
insert into CLUB_ALIAS
  set
  CLUB_NAME = 'IOWA DX AND CONTEST CLUB',
  ALIAS = 'IOWA DX AND CONTEST CLUB',
  CLUB_ID = (select ID from CLUB where NAME = 'IOWA DX AND CONTEST CLUB');
insert into CLUB_ALIAS
  set
  CLUB_NAME = 'CONTEST CLUB ONTARIO',
  ALIAS = 'CCO - CONTEST CLUB ONTARIO',
  CLUB_ID = (select ID from CLUB where NAME = 'CONTEST CLUB ONTARIO');
insert into CLUB_ALIAS
  set
  CLUB_NAME = 'NORTH TEXAS DX CONTEST CLUB',
  ALIAS = 'NORTH TEXAS DX CONTEST CLUB',
  CLUB_ID = (select ID from CLUB where NAME = 'NORTH TEXAS DX CONTEST CLUB');
insert into CLUB_ALIAS
  set
  CLUB_NAME = 'CJDXA',
  ALIAS = 'CJDXA',
  CLUB_ID = (select ID from CLUB where NAME = 'CJDXA');
insert into CLUB_ALIAS
  set
  CLUB_NAME = 'GRUPO ARGENTINO DE RADIOTELEGRAFIA (GACW)',
  ALIAS = 'GACW',
  CLUB_ID = (select ID from CLUB where NAME = 'GRUPO ARGENTINO DE RADIOTELEGRAFIA (GACW)');
insert into CLUB_ALIAS
  set
  CLUB_NAME = 'REDWOOD EMPIRE DX ASSOCIATION',
  ALIAS = 'REDWOOD EMPIRE DX ASSN',
  CLUB_ID = (select ID from CLUB where NAME = 'REDWOOD EMPIRE DX ASSOCIATION');
insert into CLUB_ALIAS
  set
  CLUB_NAME = 'NONE SPECIFIED',
  ALIAS = 'NONE-CA',
  CLUB_ID = (select ID from CLUB where NAME = 'NONE SPECIFIED');
insert into CLUB_ALIAS
  set
  CLUB_NAME = 'MOTHER LODE DX AND CONTEST CLUB',
  ALIAS = 'MOTHER LODE DX &AMP; CONTEST CLUB',
  CLUB_ID = (select ID from CLUB where NAME = 'MOTHER LODE DX AND CONTEST CLUB');
insert into CLUB_ALIAS
  set
  CLUB_NAME = 'NORTHERN CALIFORNIA CONTEST CLUB',
  ALIAS = 'NORTHERN CALIF. CONTEST CLUB',
  CLUB_ID = (select ID from CLUB where NAME = 'NORTHERN CALIFORNIA CONTEST CLUB');
insert into CLUB_ALIAS
  set
  CLUB_NAME = 'MANTECA  AMATEUR RADIO CLUB',
  ALIAS = 'MANTECA  AMATEUR RADIO CLUB',
  CLUB_ID = (select ID from CLUB where NAME = 'MANTECA  AMATEUR RADIO CLUB');
insert into CLUB_ALIAS
  set
  CLUB_NAME = 'TENNESSEE CONTEST GROUP',
  ALIAS = 'TENNESSEE CONTES GROUP',
  CLUB_ID = (select ID from CLUB where NAME = 'TENNESSEE CONTEST GROUP');
insert into CLUB_ALIAS
  set
  CLUB_NAME = 'WEST PARK RADIOPS',
  ALIAS = 'WEST PARK RADIOPS',
  CLUB_ID = (select ID from CLUB where NAME = 'WEST PARK RADIOPS');
insert into CLUB_ALIAS
  set
  CLUB_NAME = 'MWA',
  ALIAS = 'MWA',
  CLUB_ID = (select ID from CLUB where NAME = 'MWA');
insert into CLUB_ALIAS
  set
  CLUB_NAME = 'YUBA SUTTER ARC',
  ALIAS = 'YUBA SUTTER ARC',
  CLUB_ID = (select ID from CLUB where NAME = 'YUBA SUTTER ARC');
insert into CLUB_ALIAS
  set
  CLUB_NAME = 'CARA',
  ALIAS = 'CARA',
  CLUB_ID = (select ID from CLUB where NAME = 'CARA');
insert into CLUB_ALIAS
  set
  CLUB_NAME = 'MONTEREY BAY AMATEUR RADIO ASSOCIATION',
  ALIAS = 'MONTEREY BAY ARC',
  CLUB_ID = (select ID from CLUB where NAME = 'MONTEREY BAY AMATEUR RADIO ASSOCIATION');
insert into CLUB_ALIAS
  set
  CLUB_NAME = 'SOUTHEAST CONTEST CLUB',
  ALIAS = 'SECC',
  CLUB_ID = (select ID from CLUB where NAME = 'SOUTHEAST CONTEST CLUB');
insert into CLUB_ALIAS
  set
  CLUB_NAME = 'POTOMAC VALLEY RADIO CLUB',
  ALIAS = 'PVRC',
  CLUB_ID = (select ID from CLUB where NAME = 'POTOMAC VALLEY RADIO CLUB');
insert into CLUB_ALIAS
  set
  CLUB_NAME = 'LOW COUNTRY CONTEST CLUB',
  ALIAS = 'LOW COUNTRY CONTEST CLUB',
  CLUB_ID = (select ID from CLUB where NAME = 'LOW COUNTRY CONTEST CLUB');
insert into CLUB_ALIAS
  set
  CLUB_NAME = 'REMINGTON HILL ARC',
  ALIAS = 'REMINGTON HILL ARC',
  CLUB_ID = (select ID from CLUB where NAME = 'REMINGTON HILL ARC');
insert into CLUB_ALIAS
  set
  CLUB_NAME = 'DXXE',
  ALIAS = 'DXXE',
  CLUB_ID = (select ID from CLUB where NAME = 'DXXE');
insert into CLUB_ALIAS
  set
  CLUB_NAME = 'SALTON SEA ARC',
  ALIAS = 'SALTON SEA ARC',
  CLUB_ID = (select ID from CLUB where NAME = 'SALTON SEA ARC');
insert into CLUB_ALIAS
  set
  CLUB_NAME = 'POTOMAC VALLEY RADIO CLUB',
  ALIAS = 'POTOMAC VALLEY RADIO CLUB',
  CLUB_ID = (select ID from CLUB where NAME = 'POTOMAC VALLEY RADIO CLUB');
insert into CLUB_ALIAS
  set
  CLUB_NAME = 'NORTHERN CALIFORNIA CONTEST CLUB',
  ALIAS = 'NCCC',
  CLUB_ID = (select ID from CLUB where NAME = 'NORTHERN CALIFORNIA CONTEST CLUB');
insert into CLUB_ALIAS
  set
  CLUB_NAME = 'REDWOOD EMPIRE DX ASSOCIATION',
  ALIAS = 'REDWOOD EMPIRE DX ASSOCIATION',
  CLUB_ID = (select ID from CLUB where NAME = 'REDWOOD EMPIRE DX ASSOCIATION');
insert into CLUB_ALIAS
  set
  CLUB_NAME = 'MINNESOTA WIRELESS ASSOCIATION',
  ALIAS = 'MINNESOTA WIRELESS ASSOCIATION',
  CLUB_ID = (select ID from CLUB where NAME = 'MINNESOTA WIRELESS ASSOCIATION');
insert into CLUB_ALIAS
  set
  CLUB_NAME = 'HUDSON VALLEY CONTESTERS AND DXERS',
  ALIAS = 'HUDSON VALLEY DXERS AND CONTESTERS',
  CLUB_ID = (select ID from CLUB where NAME = 'HUDSON VALLEY CONTESTERS AND DXERS');
insert into CLUB_ALIAS
  set
  CLUB_NAME = 'WILLAMETTE VALLEY DX CLUB',
  ALIAS = 'WILLAMETTE VALLEY DX CLUB',
  CLUB_ID = (select ID from CLUB where NAME = 'WILLAMETTE VALLEY DX CLUB');
insert into CLUB_ALIAS
  set
  CLUB_NAME = 'MOTHER LODE DX AND CONTEST CLUB',
  ALIAS = 'MOTHER LODE DX/CC',
  CLUB_ID = (select ID from CLUB where NAME = 'MOTHER LODE DX AND CONTEST CLUB');
insert into CLUB_ALIAS
  set
  CLUB_NAME = 'VADXCC',
  ALIAS = 'VADXCC',
  CLUB_ID = (select ID from CLUB where NAME = 'VADXCC');
insert into CLUB_ALIAS
  set
  CLUB_NAME = 'MONTEREY BAY AMATEUR RADIO ASSOCIATION',
  ALIAS = 'MONTEREY BAY AMATEUR RADIO ASSOCIATION',
  CLUB_ID = (select ID from CLUB where NAME = 'MONTEREY BAY AMATEUR RADIO ASSOCIATION');
insert into CLUB_ALIAS
  set
  CLUB_NAME = 'WIRELESS ASSN OF SOUTH HILLS',
  ALIAS = 'WIRELESS ASSN OF SOUTH HILLS',
  CLUB_ID = (select ID from CLUB where NAME = 'WIRELESS ASSN OF SOUTH HILLS');
insert into CLUB_ALIAS
  set
  CLUB_NAME = 'REDWOOD EMPIRE DX ASSOCIATION',
  ALIAS = 'REDWOOD EMPIRE DX ASSN.',
  CLUB_ID = (select ID from CLUB where NAME = 'REDWOOD EMPIRE DX ASSOCIATION');
insert into CLUB_ALIAS
  set
  CLUB_NAME = 'FRESNO AMATEUR RADIO CLUB',
  ALIAS = 'FRESNO AMATEUR RADIO CLUB',
  CLUB_ID = (select ID from CLUB where NAME = 'FRESNO AMATEUR RADIO CLUB');
insert into CLUB_ALIAS
  set
  CLUB_NAME = 'SAN FERNANDO VALLEY ARC',
  ALIAS = 'SAN FERNANDO VALLEY ARC',
  CLUB_ID = (select ID from CLUB where NAME = 'SAN FERNANDO VALLEY ARC');
insert into CLUB_ALIAS
  set
  CLUB_NAME = 'MAD RIVER RADIO CLUB',
  ALIAS = 'MAD RIVER RADIO CLUB',
  CLUB_ID = (select ID from CLUB where NAME = 'MAD RIVER RADIO CLUB');
insert into CLUB_ALIAS
  set
  CLUB_NAME = 'VLADIVOSTOK ARC',
  ALIAS = 'VLADIVOSTOK ARC',
  CLUB_ID = (select ID from CLUB where NAME = 'VLADIVOSTOK ARC');
insert into CLUB_ALIAS
  set
  CLUB_NAME = 'WESTERN WASHINGTON DX CLUB',
  ALIAS = 'WESTERN WASHINGTON DX CLUB',
  CLUB_ID = (select ID from CLUB where NAME = 'WESTERN WASHINGTON DX CLUB');
insert into CLUB_ALIAS
  set
  CLUB_NAME = 'MINNESOTA WIRELESS ASSOCIATION',
  ALIAS = 'MINNESOTA WIRELESS ASSN',
  CLUB_ID = (select ID from CLUB where NAME = 'MINNESOTA WIRELESS ASSOCIATION');
insert into CLUB_ALIAS
  set
  CLUB_NAME = 'YUMA DX ASSOCIATION',
  ALIAS = 'YUMA DX ASSOCIATION',
  CLUB_ID = (select ID from CLUB where NAME = 'YUMA DX ASSOCIATION');
insert into CLUB_ALIAS
  set
  CLUB_NAME = 'REDWOOD EMPIRE DX ASSOCIATION',
  ALIAS = 'REDWOOD EMPIRE DX ASSN',
  CLUB_ID = (select ID from CLUB where NAME = 'REDWOOD EMPIRE DX ASSOCIATION');
insert into CLUB_ALIAS
  set
  CLUB_NAME = 'CONTEST CLUB ONTARIO',
  ALIAS = 'CONTEST CLUB OF ONTARIO',
  CLUB_ID = (select ID from CLUB where NAME = 'CONTEST CLUB ONTARIO');
insert into CLUB_ALIAS
  set
  CLUB_NAME = 'CENTRAL ARIZONA DX ASSN',
  ALIAS = 'CENTRAL ARIZONA DX ASSN',
  CLUB_ID = (select ID from CLUB where NAME = 'CENTRAL ARIZONA DX ASSN');
insert into CLUB_ALIAS
  set
  CLUB_NAME = 'CONTEST CLUB ONTARIO',
  ALIAS = 'CONTEST CLUB ONTARIO',
  CLUB_ID = (select ID from CLUB where NAME = 'CONTEST CLUB ONTARIO');
insert into CLUB_ALIAS
  set
  CLUB_NAME = 'SMARC',
  ALIAS = 'SMARC',
  CLUB_ID = (select ID from CLUB where NAME = 'SMARC');
insert into CLUB_ALIAS
  set
  CLUB_NAME = 'NORTHERN CALIFORNIA CONTEST CLUB',
  ALIAS = 'NORTHERN CALIFORNIA CONTEST CLUB',
  CLUB_ID = (select ID from CLUB where NAME = 'NORTHERN CALIFORNIA CONTEST CLUB');
insert into CLUB_ALIAS
  set
  CLUB_NAME = 'SOUTHEAST CONTEST CLUB',
  ALIAS = 'SOUTH EAST CONTEST CLUB',
  CLUB_ID = (select ID from CLUB where NAME = 'SOUTHEAST CONTEST CLUB');
insert into CLUB_ALIAS
  set
  CLUB_NAME = 'MARITIME CONTEST CLUB',
  ALIAS = 'MARITIME CONTEST CLUB',
  CLUB_ID = (select ID from CLUB where NAME = 'MARITIME CONTEST CLUB');
insert into CLUB_ALIAS
  set
  CLUB_NAME = 'NORTHERN CALIFORNIA CONTEST CLUB',
  ALIAS = 'NORTERN CALIFORNIA CONTEST CLUB',
  CLUB_ID = (select ID from CLUB where NAME = 'NORTHERN CALIFORNIA CONTEST CLUB');
insert into CLUB_ALIAS
  set
  CLUB_NAME = 'YANKEE CLIPPER CONTEST CLUB',
  ALIAS = 'YANKEE CLIPPER CONTEST CLUB',
  CLUB_ID = (select ID from CLUB where NAME = 'YANKEE CLIPPER CONTEST CLUB');
insert into CLUB_ALIAS
  set
  CLUB_NAME = 'ORARI',
  ALIAS = 'ORARI',
  CLUB_ID = (select ID from CLUB where NAME = 'ORARI');
insert into CLUB_ALIAS
  set
  CLUB_NAME = 'REDWOOD EMPIRE DX ASSOCIATION',
  ALIAS = 'REDWOOD EMPIRE DX ASSOCN',
  CLUB_ID = (select ID from CLUB where NAME = 'REDWOOD EMPIRE DX ASSOCIATION');
insert into CLUB_ALIAS
  set
  CLUB_NAME = 'UTAH DX ASSN',
  ALIAS = 'UTAH DX ASSN',
  CLUB_ID = (select ID from CLUB where NAME = 'UTAH DX ASSN');
insert into CLUB_ALIAS
  set
  CLUB_NAME = 'POTOMAC VALLEY RADIO CLUB',
  ALIAS = 'POTOMAC VALLEY RADIO CLUB',
  CLUB_ID = (select ID from CLUB where NAME = 'POTOMAC VALLEY RADIO CLUB');
insert into CLUB_ALIAS
  set
  CLUB_NAME = 'FOSSIL FALLS PEANUT WHISTLES',
  ALIAS = 'AMATEUR RADIO CLUB OF ALAMEDA',
  CLUB_ID = (select ID from CLUB where NAME = 'FOSSIL FALLS PEANUT WHISTLES');
insert into CLUB_ALIAS
  set
  CLUB_NAME = 'OKLAHOMA DX ASSN',
  ALIAS = 'OKLAHOMA DX ASSN',
  CLUB_ID = (select ID from CLUB where NAME = 'OKLAHOMA DX ASSN');
insert into CLUB_ALIAS
  set
  CLUB_NAME = 'SOUTHEAST CONTEST CLUB',
  ALIAS = 'SOUTH EAST CONTEST CLUB',
  CLUB_ID = (select ID from CLUB where NAME = 'SOUTHEAST CONTEST CLUB');
insert into CLUB_ALIAS
  set
  CLUB_NAME = 'NONE SPECIFIED',
  ALIAS = 'NONE-OT',
  CLUB_ID = (select ID from CLUB where NAME = 'NONE SPECIFIED');
insert into CLUB_ALIAS
  set
  CLUB_NAME = 'FRANKFORD RADIO CLUB',
  ALIAS = 'FRANKFORD RADIO CLUB',
  CLUB_ID = (select ID from CLUB where NAME = 'FRANKFORD RADIO CLUB');
insert into CLUB_ALIAS
  set
  CLUB_NAME = 'CTRI CONTEST GROUP',
  ALIAS = 'CTRI CONTEST GROUP',
  CLUB_ID = (select ID from CLUB where NAME = 'CTRI CONTEST GROUP');
insert into CLUB_ALIAS
  set
  CLUB_NAME = 'REDWOOD EMPIRE DX ASSOCIATION',
  ALIAS = 'REDWOD EMPIRE DX ASSOCIATION',
  CLUB_ID = (select ID from CLUB where NAME = 'REDWOOD EMPIRE DX ASSOCIATION');
insert into CLUB_ALIAS
  set
  CLUB_NAME = 'HAT IN HAND CONTEST CLUB',
  ALIAS = 'HAT IN HAND CONTEST CLUB',
  CLUB_ID = (select ID from CLUB where NAME = 'HAT IN HAND CONTEST CLUB');
insert into CLUB_ALIAS
  set
  CLUB_NAME = 'MONTEREY BAY AMATEUR RADIO ASSOCIATION',
  ALIAS = 'MBARA',
  CLUB_ID = (select ID from CLUB where NAME = 'MONTEREY BAY AMATEUR RADIO ASSOCIATION');
insert into CLUB_ALIAS
  set
  CLUB_NAME = 'CONTEST CLUB ONTARIO',
  ALIAS = 'CONTEST  CLUB  ONTARIO',
  CLUB_ID = (select ID from CLUB where NAME = 'CONTEST CLUB ONTARIO');
insert into CLUB_ALIAS
  set
  CLUB_NAME = 'SOUTHERN CALIFORNIA AMATEUR TRANSMITTING SOCIETY',
  ALIAS = 'SOUTHERN CALIFORNIA AMATUER TRANSMITTING SOCIETY',
  CLUB_ID = (select ID from CLUB where NAME = 'SOUTHERN CALIFORNIA AMATEUR TRANSMITTING SOCIETY');
insert into CLUB_ALIAS
  set
  CLUB_NAME = 'RUSSIAN CONTEST CLUB',
  ALIAS = 'RUSSIAN CONTEST CLUB',
  CLUB_ID = (select ID from CLUB where NAME = 'RUSSIAN CONTEST CLUB');
insert into CLUB_ALIAS
  set
  CLUB_NAME = 'REDWOOD EMPIRE DX ASSOCIATION',
  ALIAS = 'REDWOOD EMPIRE DX ASSOCATION',
  CLUB_ID = (select ID from CLUB where NAME = 'REDWOOD EMPIRE DX ASSOCIATION');
insert into CLUB_ALIAS
  set
  CLUB_NAME = 'POTOMAC VALLEY RADIO CLUB',
  ALIAS = 'PVRC',
  CLUB_ID = (select ID from CLUB where NAME = 'POTOMAC VALLEY RADIO CLUB');
insert into CLUB_ALIAS
  set
  CLUB_NAME = 'GRAND MESA CONTESTERS OF COLORADO',
  ALIAS = 'GRAND MESA CONTESTERS OF COLORADO',
  CLUB_ID = (select ID from CLUB where NAME = 'GRAND MESA CONTESTERS OF COLORADO');
insert into CLUB_ALIAS
  set
  CLUB_NAME = 'MONTEREY BAY AMATEUR RADIO ASSOCIATION',
  ALIAS = 'MBARA (MONTEREY BAY AMATEUR RADIO ASSOCIATION)',
  CLUB_ID = (select ID from CLUB where NAME = 'MONTEREY BAY AMATEUR RADIO ASSOCIATION');
insert into CLUB_ALIAS
  set
  CLUB_NAME = 'WVDXC',
  ALIAS = 'WVDXC',
  CLUB_ID = (select ID from CLUB where NAME = 'WVDXC');
