insert into MULTIPLIER (NAME,DESCRIPTION,TYPE) values ('ALAM','Alameda','COUNTY');
insert into MULTIPLIER (NAME,DESCRIPTION,TYPE) values ('ALPI','Alpine','COUNTY');
insert into MULTIPLIER (NAME,DESCRIPTION,TYPE) values ('AMAD','Amador','COUNTY');
insert into MULTIPLIER (NAME,DESCRIPTION,TYPE) values ('BUTT','Butte','COUNTY');
insert into MULTIPLIER (NAME,DESCRIPTION,TYPE) values ('CALA','Calaveras','COUNTY');
insert into MULTIPLIER (NAME,DESCRIPTION,TYPE) values ('COLU','Colusa','COUNTY');
insert into MULTIPLIER (NAME,DESCRIPTION,TYPE) values ('CCOS','Contra Costa','COUNTY');
insert into MULTIPLIER (NAME,DESCRIPTION,TYPE) values ('DELN','Del Norte','COUNTY');
insert into MULTIPLIER (NAME,DESCRIPTION,TYPE) values ('ELDO','El Dorado','COUNTY');
insert into MULTIPLIER (NAME,DESCRIPTION,TYPE) values ('FRES','Fresno','COUNTY');
insert into MULTIPLIER (NAME,DESCRIPTION,TYPE) values ('GLEN','Glenn','COUNTY');
insert into MULTIPLIER (NAME,DESCRIPTION,TYPE) values ('HUMB','Humboldt','COUNTY');
insert into MULTIPLIER (NAME,DESCRIPTION,TYPE) values ('IMPE','Imperial','COUNTY');
insert into MULTIPLIER (NAME,DESCRIPTION,TYPE) values ('INYO','Inyo','COUNTY');
insert into MULTIPLIER (NAME,DESCRIPTION,TYPE) values ('KERN','Kern','COUNTY');
insert into MULTIPLIER (NAME,DESCRIPTION,TYPE) values ('KING','Kings','COUNTY');
insert into MULTIPLIER (NAME,DESCRIPTION,TYPE) values ('LAKE','Lake','COUNTY');
insert into MULTIPLIER (NAME,DESCRIPTION,TYPE) values ('LASS','Lassen','COUNTY');
insert into MULTIPLIER (NAME,DESCRIPTION,TYPE) values ('LANG','Los Angeles','COUNTY');
insert into MULTIPLIER (NAME,DESCRIPTION,TYPE) values ('MADE','Madera','COUNTY');
insert into MULTIPLIER (NAME,DESCRIPTION,TYPE) values ('MARN','Marin','COUNTY');
insert into MULTIPLIER (NAME,DESCRIPTION,TYPE) values ('MARP','Mariposa','COUNTY');
insert into MULTIPLIER (NAME,DESCRIPTION,TYPE) values ('MEND','Mendocino','COUNTY');
insert into MULTIPLIER (NAME,DESCRIPTION,TYPE) values ('MERC','Merced','COUNTY');
insert into MULTIPLIER (NAME,DESCRIPTION,TYPE) values ('MODO','Modoc','COUNTY');
insert into MULTIPLIER (NAME,DESCRIPTION,TYPE) values ('MONO','Mono','COUNTY');
insert into MULTIPLIER (NAME,DESCRIPTION,TYPE) values ('MONT','Monterey','COUNTY');
insert into MULTIPLIER (NAME,DESCRIPTION,TYPE) values ('NAPA','Napa','COUNTY');
insert into MULTIPLIER (NAME,DESCRIPTION,TYPE) values ('NEVA','Nevada','COUNTY');
insert into MULTIPLIER (NAME,DESCRIPTION,TYPE) values ('ORAN','Orange','COUNTY');
insert into MULTIPLIER (NAME,DESCRIPTION,TYPE) values ('PLAC','Placer','COUNTY');
insert into MULTIPLIER (NAME,DESCRIPTION,TYPE) values ('PLUM','Plumas','COUNTY');
insert into MULTIPLIER (NAME,DESCRIPTION,TYPE) values ('RIVE','Riverside','COUNTY');
insert into MULTIPLIER (NAME,DESCRIPTION,TYPE) values ('SACR','Sacramento','COUNTY');
insert into MULTIPLIER (NAME,DESCRIPTION,TYPE) values ('SBEN','San Benito','COUNTY');
insert into MULTIPLIER (NAME,DESCRIPTION,TYPE) values ('SBER','San Bernardino','COUNTY');
insert into MULTIPLIER (NAME,DESCRIPTION,TYPE) values ('SDIE','San Diego','COUNTY');
insert into MULTIPLIER (NAME,DESCRIPTION,TYPE) values ('SFRA','San Francisco','COUNTY');
insert into MULTIPLIER (NAME,DESCRIPTION,TYPE) values ('SJOA','San Joaquin','COUNTY');
insert into MULTIPLIER (NAME,DESCRIPTION,TYPE) values ('SLUI','San Luis Obispo','COUNTY');
insert into MULTIPLIER (NAME,DESCRIPTION,TYPE) values ('SMAT','San Mateo','COUNTY');
insert into MULTIPLIER (NAME,DESCRIPTION,TYPE) values ('SBAR','Santa Barbara','COUNTY');
insert into MULTIPLIER (NAME,DESCRIPTION,TYPE) values ('SCLA','Santa Clara','COUNTY');
insert into MULTIPLIER (NAME,DESCRIPTION,TYPE) values ('SCRU','Santa Cruz','COUNTY');
insert into MULTIPLIER (NAME,DESCRIPTION,TYPE) values ('SHAS','Shasta','COUNTY');
insert into MULTIPLIER (NAME,DESCRIPTION,TYPE) values ('SIER','Sierra','COUNTY');
insert into MULTIPLIER (NAME,DESCRIPTION,TYPE) values ('SISK','Siskiyou','COUNTY');
insert into MULTIPLIER (NAME,DESCRIPTION,TYPE) values ('SOLA','Solano','COUNTY');
insert into MULTIPLIER (NAME,DESCRIPTION,TYPE) values ('SONO','Sonoma','COUNTY');
insert into MULTIPLIER (NAME,DESCRIPTION,TYPE) values ('STAN','Stanislaus','COUNTY');
insert into MULTIPLIER (NAME,DESCRIPTION,TYPE) values ('SUTT','Sutter','COUNTY');
insert into MULTIPLIER (NAME,DESCRIPTION,TYPE) values ('TEHA','Tehama','COUNTY');
insert into MULTIPLIER (NAME,DESCRIPTION,TYPE) values ('TRIN','Trinity','COUNTY');
insert into MULTIPLIER (NAME,DESCRIPTION,TYPE) values ('TULA','Tulare','COUNTY');
insert into MULTIPLIER (NAME,DESCRIPTION,TYPE) values ('TUOL','Tuolumne','COUNTY');
insert into MULTIPLIER (NAME,DESCRIPTION,TYPE) values ('VENT','Ventura','COUNTY');
insert into MULTIPLIER (NAME,DESCRIPTION,TYPE) values ('YOLO','Yolo','COUNTY');
insert into MULTIPLIER (NAME,DESCRIPTION,TYPE) values ('YUBA','Yuba','COUNTY');
commit;
update MULTIPLIER set VALUE = 1 where TYPE = 'COUNTY';
commit;
insert into MULTIPLIER (NAME,DESCRIPTION,VALUE,TYPE) values ('AL','Alabama',1,'STATE');         
insert into MULTIPLIER (NAME,DESCRIPTION,VALUE,TYPE) values ('AK','Alaska',1,'STATE');         
insert into MULTIPLIER (NAME,DESCRIPTION,VALUE,TYPE) values ('AZ','Arizona',1,'STATE');         
insert into MULTIPLIER (NAME,DESCRIPTION,VALUE,TYPE) values ('AR','Arkansas',1,'STATE');         
insert into MULTIPLIER (NAME,DESCRIPTION,VALUE,TYPE) values ('CA','California',1,'STATE');         
insert into MULTIPLIER (NAME,DESCRIPTION,VALUE,TYPE) values ('CO','Colorado',1,'STATE');         
insert into MULTIPLIER (NAME,DESCRIPTION,VALUE,TYPE) values ('CT','Connecticut',1,'STATE');         
insert into MULTIPLIER (NAME,DESCRIPTION,VALUE,TYPE) values ('DE','Delaware',1,'STATE');         
insert into MULTIPLIER (NAME,DESCRIPTION,VALUE,TYPE) values ('FL','Florida',1,'STATE');         
insert into MULTIPLIER (NAME,DESCRIPTION,VALUE,TYPE) values ('GA','Georgia',1,'STATE');         
insert into MULTIPLIER (NAME,DESCRIPTION,VALUE,TYPE) values ('HI','Hawaii',1,'STATE');         
insert into MULTIPLIER (NAME,DESCRIPTION,VALUE,TYPE) values ('ID','Idaho',1,'STATE');         
insert into MULTIPLIER (NAME,DESCRIPTION,VALUE,TYPE) values ('IL','Illinois',1,'STATE');         
insert into MULTIPLIER (NAME,DESCRIPTION,VALUE,TYPE) values ('IN','Indiana',1,'STATE');         
insert into MULTIPLIER (NAME,DESCRIPTION,VALUE,TYPE) values ('IA','Iowa',1,'STATE');         
insert into MULTIPLIER (NAME,DESCRIPTION,VALUE,TYPE) values ('KS','Kansas',1,'STATE');         
insert into MULTIPLIER (NAME,DESCRIPTION,VALUE,TYPE) values ('KY','Kentucky',1,'STATE');         
insert into MULTIPLIER (NAME,DESCRIPTION,VALUE,TYPE) values ('LA','Louisiana',1,'STATE');         
insert into MULTIPLIER (NAME,DESCRIPTION,VALUE,TYPE) values ('ME','Maine',1,'STATE');         
insert into MULTIPLIER (NAME,DESCRIPTION,VALUE,TYPE) values ('MD','Maryland',1,'STATE');         
insert into MULTIPLIER (NAME,DESCRIPTION,VALUE,TYPE) values ('MA','Massachusetts',1,'STATE');         
insert into MULTIPLIER (NAME,DESCRIPTION,VALUE,TYPE) values ('MI','Michigan',1,'STATE');         
insert into MULTIPLIER (NAME,DESCRIPTION,VALUE,TYPE) values ('MN','Minnesota',1,'STATE');         
insert into MULTIPLIER (NAME,DESCRIPTION,VALUE,TYPE) values ('MS','Mississippi',1,'STATE');         
insert into MULTIPLIER (NAME,DESCRIPTION,VALUE,TYPE) values ('MO','Missouri',1,'STATE');         
insert into MULTIPLIER (NAME,DESCRIPTION,VALUE,TYPE) values ('MT','Montana',1,'STATE');         
insert into MULTIPLIER (NAME,DESCRIPTION,VALUE,TYPE) values ('NE','Nebraska',1,'STATE');         
insert into MULTIPLIER (NAME,DESCRIPTION,VALUE,TYPE) values ('NV','Nevada',1,'STATE');         
insert into MULTIPLIER (NAME,DESCRIPTION,VALUE,TYPE) values ('NH','New Hampshire',1,'STATE');         
insert into MULTIPLIER (NAME,DESCRIPTION,VALUE,TYPE) values ('NJ','New Jersey',1,'STATE');         
insert into MULTIPLIER (NAME,DESCRIPTION,VALUE,TYPE) values ('NM','New Mexico',1,'STATE');         
insert into MULTIPLIER (NAME,DESCRIPTION,VALUE,TYPE) values ('NY','New York',1,'STATE');         
insert into MULTIPLIER (NAME,DESCRIPTION,VALUE,TYPE) values ('NC','North Carolina',1,'STATE');         
insert into MULTIPLIER (NAME,DESCRIPTION,VALUE,TYPE) values ('ND','North Dakota',1,'STATE');         
insert into MULTIPLIER (NAME,DESCRIPTION,VALUE,TYPE) values ('OH','Ohio',1,'STATE');         
insert into MULTIPLIER (NAME,DESCRIPTION,VALUE,TYPE) values ('OK','Oklahoma',1,'STATE');         
insert into MULTIPLIER (NAME,DESCRIPTION,VALUE,TYPE) values ('OR','Oregon',1,'STATE');         
insert into MULTIPLIER (NAME,DESCRIPTION,VALUE,TYPE) values ('PA','Pennsylvania',1,'STATE');         
insert into MULTIPLIER (NAME,DESCRIPTION,VALUE,TYPE) values ('RI','Rhode Island',1,'STATE');         
insert into MULTIPLIER (NAME,DESCRIPTION,VALUE,TYPE) values ('SC','South Carolina',1,'STATE');         
insert into MULTIPLIER (NAME,DESCRIPTION,VALUE,TYPE) values ('SD','South Dakota',1,'STATE');         
insert into MULTIPLIER (NAME,DESCRIPTION,VALUE,TYPE) values ('TN','Tennessee',1,'STATE');         
insert into MULTIPLIER (NAME,DESCRIPTION,VALUE,TYPE) values ('TX','Texas',1,'STATE');         
insert into MULTIPLIER (NAME,DESCRIPTION,VALUE,TYPE) values ('UT','Utah',1,'STATE');         
insert into MULTIPLIER (NAME,DESCRIPTION,VALUE,TYPE) values ('VT','Vermont',1,'STATE');         
insert into MULTIPLIER (NAME,DESCRIPTION,VALUE,TYPE) values ('VA','Virginia',1,'STATE');         
insert into MULTIPLIER (NAME,DESCRIPTION,VALUE,TYPE) values ('WA','Washington',1,'STATE');         
insert into MULTIPLIER (NAME,DESCRIPTION,VALUE,TYPE) values ('WV','West Virginia',1,'STATE');         
insert into MULTIPLIER (NAME,DESCRIPTION,VALUE,TYPE) values ('WI','Wisconsin',1,'STATE');         
insert into MULTIPLIER (NAME,DESCRIPTION,VALUE,TYPE) values ('WY','Wyoming',1,'STATE');         
insert into MULTIPLIER (NAME,DESCRIPTION,VALUE,TYPE) values ('MR','Maritimes',1,'PROVINCE');         
insert into MULTIPLIER (NAME,DESCRIPTION,VALUE,TYPE) values ('QC','Quebec',1,'PROVINCE');         
insert into MULTIPLIER (NAME,DESCRIPTION,VALUE,TYPE) values ('ON','Ontario',1,'PROVINCE');         
insert into MULTIPLIER (NAME,DESCRIPTION,VALUE,TYPE) values ('MB','Manitoba',1,'PROVINCE');         
insert into MULTIPLIER (NAME,DESCRIPTION,VALUE,TYPE) values ('SK','Saskatchewan',1,'PROVINCE');         
insert into MULTIPLIER (NAME,DESCRIPTION,VALUE,TYPE) values ('AB','Alberta',1,'PROVINCE');         
insert into MULTIPLIER (NAME,DESCRIPTION,VALUE,TYPE) values ('BC','British Columbia',1,'PROVINCE');         
insert into MULTIPLIER (NAME,DESCRIPTION,VALUE,TYPE) values ('NT','Northern Territories',1,'PROVINCE');
insert into MULTIPLIER (NAME,DESCRIPTION,VALUE,TYPE) values ('DX','DX Country',0,'COUNTRY');
commit;
