
package CQP_clubs;

#define the hashes
%club_name_to_ID = ();
%ID_to_club_name = ();


%club_name_to_ID = (
'MLDXCC',CLBCA10,
'Mother Load DX and Contest Club',CLBCA10,
'Motherlode',CLBCA10,
'Mother Lode DX &amp; CC',CLBCA10,
'Mother Lode DX &amp; Contest Club',CLBCA10,
'Mother Lode DX and Contest club',CLBCA10,
'MOTHERLODE DX AND CONTEST CLUB (MLDXCC)',CLBCA10,
'Mother Lode DX/CC',CLBCA10,
'Mother Lode DXCC',CLBCA10,
'Motherlode DX/Contest Club',CLBCA10,
'Mother Lode DX/Contest Club',CLBCA10,
'Russian Contest Club',CLBOT11,
'CARA',CLBOT12,
'British Columbia DX Club',CLBOT13,
'Maritime Contest Club',CLBOT14,
'CCO',CLBOT15,
'CCO - Contest Club Ontario',CLBOT15,
'CCO Contest Club Ontario',CLBOT15,
'Contest Club of Ontario',CLBOT15,
'Contest  Club  Ontario',CLBOT15,
'Contest Club Ontario',CLBOT15,
'CONTEST CLUB ONTARIO',CLBOT15,
'Calgary Amateur Radio Assoc.',CLBOT16,
'Alberta Clippers',CLBOT17,
'Boulder ARC',CLBOT18,
'West Jersey DX Club',CLBOT19,
'Frankford Radio Club',CLBOT20,
'FRANKFORD RADIO CLUB',CLBOT20,
'FRC',CLBOT20,
'North Hills Amateur Radio Contest Society',CLBOT21,
'Twin City Ham Club',CLBOT22,
'Nevada Country Amateur Radio Club',CLBCA23,
'Fresno Amateur Radio Club',CLBCA24,
'San Fernando Valley ARC',CLBCA25,
'YUBA SUTTER ARC',CLBCA26,
'Hat in Hand Contest Club',CLBCA27,
'Stanford Amateur Radio Club',CLBCA28,
'Central Arizona DX Assn',CLBOT29,
'Escondido Amateur Radio Society',CLBCA30,
'SCCARC',CLBCA31,
'Potomac Valley Radio Club',CLBOT32,
'Potomac Valley Radio CLub',CLBOT32,
'POTOMAC VALLEY RADIO CLUB',CLBOT32,
'PVRC',CLBOT32,
'pvrc',CLBOT32,
'USC Amateur Radio Club',CLBCA33,
'VADXCC',CLBOT34,
'North Coast Contesters',CLBOT35,
'West Park Radiops',CLBOT36,
'Metro DX Club',CLBOT37,
'North Texas Microwave Society',CLBOT38,
'WyDXCC',CLBOT39,
'North Texas Contest Club',CLBOT40,
'DXXE',CLBOT41,
'ORARI',CLBOT42,
'Radioclub Transylvania Connection',CLBOT43,
'URE',CLBOT44,
'CJDXA',CLBOT45,
'SMC',CLBOT46,
'Society of Midwest Contesters',CLBOT46,
'SOCIETY OF MIDWEST CONTESTERS',CLBOT46,
'Society of Midwestern Contesters',CLBOT46,
'Low Country Contest Club',CLBOT47,
'Minnesota Wireless Assn',CLBOT48,
'Minnesota Wireless Assoc',CLBOT48,
'Minnesota Wireless Association',CLBOT48,
'MN WIRELESS ASSN',CLBOT48,
'Grand Mesa Contesters of Colorado',CLBOT49,
'GRAND MESA CONTESTERS OF COLORADO',CLBOT49,
'Yankee Clipper Contest Club',CLBOT50,
'YCCC',CLBOT50,
'RAE',CLBOT51,
'Wireless Assn of South Hills',CLBOT52,
'MWA',CLBOT53,
'Florida Contest Group',CLBOT54,
'FLORIDA CONTEST GROUP',CLBOT54,
'Alabama Contest Group',CLBOT55,
'SECC',CLBOT56,
'Southeast Contest Club',CLBOT56,
'South East Contest Club',CLBOT56,
'SOUTH EAST CONTEST CLUB',CLBOT56,
'SOUTHEAST CONTEST CLUB',CLBOT56,
'Central OR DX Club',CLBOT57,
'OKDXA',CLBOT58,
'Oklahoma DX Assn',CLBOT58,
'Central Texas DX and Contest Club',CLBOT59,
'SMARC',CLBOT60,
'Doggie Op G',CLBOT61,
'Southern Marin Amateur Radio Trans. Society',CLBCA62,
'Manteca  AMATEUR RADIO CLUB',CLBCA63,
'NCCC',CLBCA64,
'Northern Calif. Contest Club',CLBCA64,
'northern california contest club',CLBCA64,
'Northern California Contest Club',CLBCA64,
'Nortern California Contest Club',CLBCA64,
'NORTHERN CALIFORNIA CONTEST CLUB',CLBCA64,
'Monterey Bay Amateur Radio Assn (MBARA)',CLBCA65,
'Monterey Bay Amateur Radio Association',CLBCA65,
'Monterey Bay ARC',CLBCA65,
'Amateur Radio Club of Alameda',CLBCA66,
'SOARA',CLBCA77,
'West Valley ARA',CLBCA94,
'MBARA (Monterey Bay Amateur Radio Association)',CLBCA65,
'MBARA (Monterey Bay ARA)',CLBCA65,
'MBARA',CLBCA65,
'Fossil Falls Peanut Whistles',CLBCA66,
'WVDXC',CLBOT67,
'Western Washington DX Club',CLBOT68,
'Utah DX Assn',CLBOT69,
'Mad River Radio Club',CLBOT70,
'MAD RIVER RADIO CLUB',CLBOT70,
'sccc',CLBCA71,
'SCCC',CLBCA71,
'Southern California Contest Club',CLBCA71,
'SOUTHERN CALIFORNIA CONTEST CLUB',CLBCA71,
'ARCECS',CLBOT72,
'CADXA',CLBOT73,
'San Diego DX Club',CLBCA74,
'GACW',CLBOT75,
'GRUPO ARGENTINO DE RADIOTELEGRAFIA (GACW)',CLBOT75,
'Willamette Valley DX Club',CLBOT76,
'Iowa DX and Contest Club',CLBOT77,
'CTRI Contest Group',CLBOT78,
'Western NY Contest Club',CLBOT79,
'Hudson Valley Contesters and DXers',CLBOT80,
'Hudson Valley DXers and Contesters',CLBOT80,
'Order of Boiled Owls of New York',CLBOT81,
'Tennessee Contes Group',CLBOT82,
'Tennessee Contest Group',CLBOT82,
'TENNESSEE CONTEST GROUP',CLBOT82,
'TDXS',CLBOT83,
'Salton Sea ARC',CLBCA84,
'North Texas DX Contest Club',CLBOT85,
'Redwod Empire DX Association',CLBCA86,
'REDwood Empire DX Asn',CLBCA86,
'Redwood Empire DX Assn.',CLBCA86,
'Redwood Empire DX Assn',CLBCA86,
"Redwood Empire DX Ass'n",CLBCA86,
'Redwood Empire DX ASSN.',CLBCA86,
'Redwood Empire DX Assocation',CLBCA86,
'Redwood Empire DX Association',CLBCA86,
'Redwood Empire DX Assocn',CLBCA86,
'REDXA',CLBCA86,
'Yuma DX Association',CLBOT87,
'Southwest Ohio DX Assn',CLBOT88,
'REMINGTON HILL ARC',CLBOT89,
'CRC',CLBOT90,
'TuPY Dx Group',CLBOT91,
'Vladivostok ARC',CLBOT92,
'United Radio Amateur Club, Inc.',CLBCA93,
'United Radio Amateur Clu',CLBCA93,
'None-CA',CLBCA94,
'None-OT',CLBOT95,
'NACHO',CLBCA96,
'Southern California Amatuer Transmitting Society',CLBCA97,

);


%ID_to_club_name = (

CLBCA10,"Mother Lode DX and Contest Club",
CLBOT11,"Russian Contest Club",
CLBOT12,"CARA",
CLBOT13,"British Columbia DX Club",
CLBOT14,"Maritime Contest Club",
CLBOT15,"Contest Club Ontario",
CLBOT16,"Calgary Amateur Radio Assoc.",
CLBOT17,"Alberta Clippers",
CLBOT18,"Boulder ARC",
CLBOT19,"West Jersey DX Club",
CLBOT20,"Frankford Radio Club",
CLBOT21,"North Hills Amateur Radio Contest Society",
CLBOT22,"Twin City Ham Club",
CLBCA23,"Nevada Country Amateur Radio Club",
CLBCA24,"Fresno Amateur Radio Club",
CLBCA25,"San Fernando Valley ARC",
CLBCA26,"YUBA SUTTER ARC",
CLBCA27,"Hat in Hand Contest Club",
CLBCA28,"Stanford Amateur Radio Club",
CLBOT29,"Central Arizona DX Assn",
CLBCA30,"Escondido Amateur Radio Society",
CLBCA31,"SCCARC",
CLBOT32,"Potomac Valley Radio Club",
CLBCA33,"USC Amateur Radio Club",
CLBOT34,"VADXCC",
CLBOT35,"North Coast Contesters",
CLBOT36,"West Park Radiops",
CLBOT37,"Metro DX Club",
CLBOT38,"North Texas Microwave Society",
CLBOT39,"WyDXCC",
CLBOT40,"North Texas Contest Club",
CLBOT41,"DXXE",
CLBOT42,"ORARI",
CLBOT43,"Radioclub Transylvania Connection",
CLBOT44,"URE",
CLBOT45,"CJDXA",
CLBOT46,"Society of Midwest Contesters",
CLBOT47,"Low Country Contest Club",
CLBOT48,"Minnesota Wireless Association",
CLBOT49,"Grand Mesa Contesters of Colorado",
CLBOT50,"Yankee Clipper Contest Club",
CLBOT51,"RAE",
CLBOT52,"Wireless Assn of South Hills",
CLBOT53,"MWA",
CLBOT54,"Florida Contest Group",
CLBOT55,"Alabama Contest Group",
CLBOT56,"Southeast Contest Club",
CLBOT57,"Central OR DX Club",
CLBOT58,"Oklahoma DX Assn",
CLBOT59,"Central Texas DX and Contest Club",
CLBOT60,"SMARC",
CLBOT61,"Doggie Op G",
CLBCA62,"Southern Marin Amateur Radio Trans. Society",
CLBCA63,"Manteca  AMATEUR RADIO CLUB",
CLBCA64,"Northern California Contest Club",
CLBCA65,"Monterey Bay Amateur Radio Association",
CLBCA66,"Amateur Radio Club of Alameda",
CLBCA77,"SOARA",
CLBCA94,"West Valley ARA",
CLBCA66,"Fossil Falls Peanut Whistles",
CLBOT67,"WVDXC",
CLBOT68,"Western Washington DX Club",
CLBOT69,"Utah DX Assn",
CLBOT70,"Mad River Radio Club",
CLBCA71,"Southern California Contest Club",
CLBOT72,"ARCECS",
CLBOT73,"CADXA",
CLBCA74,"San Diego DX Club",
CLBOT75,"GRUPO ARGENTINO DE RADIOTELEGRAFIA (GACW)",
CLBOT76,"Willamette Valley DX Club",
CLBOT77,"Iowa DX and Contest Club",
CLBOT78,"CTRI Contest Group",
CLBOT79,"Western NY Contest Club",
CLBOT80,"Hudson Valley Contesters and DXers",
CLBOT81,"Order of Boiled Owls of New York",
CLBOT82,"Tennessee Contest Group",
CLBOT83,"TDXS",
CLBCA84,"Salton Sea ARC",
CLBOT85,"North Texas DX Contest Club",
CLBCA86,"Redwood Empire DX Association",
CLBOT87,"Yuma DX Association",
CLBOT88,"Southwest Ohio DX Assn",
CLBOT89,"REMINGTON HILL ARC",
CLBOT90,"CRC",
CLBOT91,"TuPY Dx Group",
CLBOT92,"Vladivostok ARC",
CLBCA93,"United Radio Amateur Club, Inc.",
CLBCA94,"None Specified",
CLBOT95,"None Specified",
CLBCA96,"NACHO",
CLBCA97,"Southern California Amateur Transmitting Society",

);


1;
