SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL';

DROP SCHEMA IF EXISTS `CQP-ACE`;
CREATE SCHEMA `CQP-ACE`;
USE `CQP-ACE`;

-- -----------------------------------------------------
-- Table `OPERATOR_CATEGORY`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `OPERATOR_CATEGORY` ;

CREATE  TABLE IF NOT EXISTS `OPERATOR_CATEGORY` (
  `ID` INT NOT NULL ,
  `NAME` VARCHAR(16) NOT NULL ,
  PRIMARY KEY (`ID`) ,
  UNIQUE INDEX `NAME_UNIQUE` (`NAME` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `POWER_CATEGORY`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `POWER_CATEGORY` ;

CREATE  TABLE IF NOT EXISTS `POWER_CATEGORY` (
  `ID` INT NOT NULL ,
  `NAME` VARCHAR(16) NOT NULL ,
  PRIMARY KEY (`ID`) ,
  UNIQUE INDEX `NAME_UNIQUE` (`NAME` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `STATION_CATEGORY`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `STATION_CATEGORY` ;

CREATE  TABLE IF NOT EXISTS `STATION_CATEGORY` (
  `ID` INT NOT NULL ,
  `NAME` VARCHAR(16) NULL ,
  PRIMARY KEY (`ID`) ,
  UNIQUE INDEX `NAME_UNIQUE` (`NAME` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TRANSMITTER_CATEGORY`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TRANSMITTER_CATEGORY` ;

CREATE  TABLE IF NOT EXISTS `TRANSMITTER_CATEGORY` (
  `ID` INT NOT NULL ,
  `NAME` VARCHAR(16) NULL ,
  PRIMARY KEY (`ID`) ,
  UNIQUE INDEX `NAME_UNIQUE` (`NAME` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OPERATOR`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `OPERATOR` ;

CREATE  TABLE IF NOT EXISTS `OPERATOR` (
  `ID` INT NOT NULL AUTO_INCREMENT ,
  `LOG_ID` INT NOT NULL ,
  `CALLSIGN` VARCHAR(16) NOT NULL ,
  `CLUB_ID` INT NULL ,
  `CLUB_ALLOCATION` INT NULL ,
  PRIMARY KEY (`ID`) ,
  INDEX `FK_OPERATOR_CLUB` (`CLUB_ID` ASC) ,
  INDEX `FK_OPERATOR_LOG` (`LOG_ID` ASC) ,
  CONSTRAINT `FK_OPERATOR_LOG`
    FOREIGN KEY (`LOG_ID` )
    REFERENCES `LOG` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CLUB`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CLUB` ;

CREATE  TABLE IF NOT EXISTS `CLUB` (
  `ID` INT NOT NULL ,
  `NAME` VARCHAR(255) NOT NULL ,
  `LOCATION` VARCHAR(4) NOT NULL ,
  PRIMARY KEY (`ID`) ,
  UNIQUE INDEX `NAME_UNIQUE` (`NAME` ASC) ,
  INDEX `FK_CLUB_OPERATOR` (`ID` ASC) ,
  CONSTRAINT `FK_CLUB_OPERATOR`
    FOREIGN KEY (`ID` )
    REFERENCES `OPERATOR` (`CLUB_ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LOG`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LOG` ;

CREATE  TABLE IF NOT EXISTS `LOG` (
  `ID` INT NOT NULL AUTO_INCREMENT ,
  `CALLSIGN` VARCHAR(16) NOT NULL ,
  `CONTEST_NAME` VARCHAR(32) NOT NULL DEFAULT 'CA-QSO-PARTY' ,
  `STATION_OWNER_CALLSIGN` VARCHAR(16) NULL ,
  `STATION_LOCATION` VARCHAR(4) NOT NULL ,
  `CONTEST_YEAR` VARCHAR(4) NOT NULL DEFAULT '2012' ,
  `OPERATOR_CATEGORY` VARCHAR(16) NOT NULL ,
  `POWER_CATEGORY` VARCHAR(16) NOT NULL ,
  `STATION_CATEGORY` VARCHAR(16) NOT NULL ,
  `TRANSMITTER_CATEGORY` VARCHAR(16) NOT NULL ,
  `CLUB` VARCHAR(255) NULL ,
  `SUBMISSION_DATE` DATE NOT NULL ,
  `OVERLAY_YL` TINYINT(1) NULL ,
  `OVERLAY_YOUTH` TINYINT(1) NULL ,
  `OVERLAY_NEW_CONTESTER` TINYINT(1) NULL ,
  `CLAIMED_SCORE` VARCHAR(32) NULL ,
  `LOG_FILENAME` VARCHAR(32) NULL ,
  `CREATE_DATE` TIMESTAMP NULL ,
  `LAST_UPDATED` TIMESTAMP NULL ,
  PRIMARY KEY (`ID`) ,
  INDEX `FK_LOG_OPERATOR_CATEGORY` (`OPERATOR_CATEGORY` ASC) ,
  INDEX `FK_LOG_POWER_CATEGORY` (`POWER_CATEGORY` ASC) ,
  INDEX `FK_LOG_STATION_CATEGORY` (`STATION_CATEGORY` ASC) ,
  INDEX `FK_LOG_TRANSMITTER_CATEGORY` (`TRANSMITTER_CATEGORY` ASC) ,
  INDEX `FK_LOG_CLUB` (`CLUB` ASC) ,
  CONSTRAINT `FK_LOG_OPERATOR_CATEGORY`
    FOREIGN KEY (`OPERATOR_CATEGORY` )
    REFERENCES `OPERATOR_CATEGORY` (`NAME` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_LOG_POWER_CATEGORY`
    FOREIGN KEY (`POWER_CATEGORY` )
    REFERENCES `POWER_CATEGORY` (`NAME` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_LOG_STATION_CATEGORY`
    FOREIGN KEY (`STATION_CATEGORY` )
    REFERENCES `STATION_CATEGORY` (`NAME` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_LOG_TRANSMITTER_CATEGORY`
    FOREIGN KEY (`TRANSMITTER_CATEGORY` )
    REFERENCES `TRANSMITTER_CATEGORY` (`NAME` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_LOG_CLUB`
    FOREIGN KEY (`CLUB` )
    REFERENCES `CLUB` (`NAME` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `QSO_STATUS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `QSO_STATUS` ;

CREATE  TABLE IF NOT EXISTS `QSO_STATUS` (
  `ID` INT NOT NULL ,
  `NAME` VARCHAR(8) NOT NULL ,
  PRIMARY KEY (`ID`) ,
  UNIQUE INDEX `NAME_UNIQUE` (`NAME` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MULTIPLIER`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MULTIPLIER` ;

CREATE  TABLE IF NOT EXISTS `MULTIPLIER` (
  `ID` INT NOT NULL AUTO_INCREMENT ,
  `NAME` VARCHAR(32) NOT NULL ,
  `TYPE` VARCHAR(16) NOT NULL ,
  `VALUE` INT(11) NOT NULL ,
  `DESCRIPTION` VARCHAR(32) NULL ,
  PRIMARY KEY (`ID`) ,
  UNIQUE INDEX `NAME_UNIQUE` (`NAME` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `QSO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `QSO` ;

CREATE  TABLE IF NOT EXISTS `QSO` (
  `ID` INT NULL AUTO_INCREMENT ,
  `QSO_DATE` DATETIME NOT NULL ,
  `CALLSIGN_SENT` VARCHAR(32) NOT NULL ,
  `CALLSIGN_RECEIVED` VARCHAR(32) NOT NULL ,
  `FREQUENCY` VARCHAR(8) NOT NULL ,
  `BAND` VARCHAR(4) NULL ,
  `MODE` VARCHAR(4) NOT NULL ,
  `SERIAL_SENT` VARCHAR(6) NOT NULL ,
  `SERIAL_RECEIVED` VARCHAR(6) NOT NULL ,
  `QTH_SENT` VARCHAR(4) NOT NULL ,
  `QTH_RECEIVED` VARCHAR(4) NOT NULL ,
  `LOG_ID` INT NOT NULL ,
  `QSO_STATUS` VARCHAR(8) NULL ,
  `CREATE_DATE` TIMESTAMP NULL ,
  `LAST_UPDATED` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ,
  PRIMARY KEY (`ID`) ,
  INDEX `FK_QSO_LOG` (`ID` ASC) ,
  INDEX `FK_QSO_QSO_STATUS` (`QSO_STATUS` ASC) ,
  INDEX `FK_QSO_QTH_RCVD_MULTIPLIER` (`QTH_RECEIVED` ASC) ,
  INDEX `FK_QSO_QTH_SENT_MULTIPLIER` (`QTH_SENT` ASC) ,
  INDEX `CALLSIGN_SENT` (`CALLSIGN_SENT` ASC) ,
  INDEX `CALLSIGN_RECEIVED` (`CALLSIGN_RECEIVED` ASC) ,
  CONSTRAINT `FK_QSO_LOG`
    FOREIGN KEY (`ID` )
    REFERENCES `LOG` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_QSO_QSO_STATUS`
    FOREIGN KEY (`QSO_STATUS` )
    REFERENCES `QSO_STATUS` (`NAME` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_QSO_QTH_RCVD_MULTIPLIER`
    FOREIGN KEY (`QTH_RECEIVED` )
    REFERENCES `MULTIPLIER` (`NAME` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_QSO_QTH_SENT_MULTIPLIER`
    FOREIGN KEY (`QTH_SENT` )
    REFERENCES `MULTIPLIER` (`NAME` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SCORE_TYPE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SCORE_TYPE` ;

CREATE  TABLE IF NOT EXISTS `SCORE_TYPE` (
  `ID` INT NOT NULL ,
  `NAME` VARCHAR(45) NULL ,
  `VALUE` VARCHAR(45) NULL ,
  PRIMARY KEY (`ID`) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SCORE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SCORE` ;

CREATE  TABLE IF NOT EXISTS `SCORE` (
  `ID` INT NOT NULL ,
  `LOG_ID` INT NOT NULL ,
  `TYPE_ID` INT NOT NULL ,
  `VALUE` VARCHAR(45) NULL ,
  PRIMARY KEY (`ID`) ,
  INDEX `FK_SCORE_LOG` (`ID` ASC) ,
  INDEX `FK_SCORE_TYPE` (`TYPE_ID` ASC) ,
  CONSTRAINT `FK_SCORE_LOG`
    FOREIGN KEY (`ID` )
    REFERENCES `LOG` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_SCORE_TYPE`
    FOREIGN KEY (`TYPE_ID` )
    REFERENCES `SCORE_TYPE` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AWARD_TYPE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AWARD_TYPE` ;

CREATE  TABLE IF NOT EXISTS `AWARD_TYPE` (
  `ID` INT NOT NULL ,
  `NAME` VARCHAR(45) NULL ,
  `VALUE` VARCHAR(45) NULL ,
  PRIMARY KEY (`ID`) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AWARD`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AWARD` ;

CREATE  TABLE IF NOT EXISTS `AWARD` (
  `ID` INT NOT NULL ,
  `LOG_ID` INT NOT NULL ,
  `TYPE_ID` INT NOT NULL ,
  `NAME` VARCHAR(64) NULL ,
  PRIMARY KEY (`ID`) ,
  INDEX `FK_AWARD_LOG` (`LOG_ID` ASC) ,
  INDEX `FK_AWARD_TYPE` (`TYPE_ID` ASC) ,
  CONSTRAINT `FK_AWARD_LOG`
    FOREIGN KEY (`LOG_ID` )
    REFERENCES `LOG` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_AWARD_TYPE`
    FOREIGN KEY (`TYPE_ID` )
    REFERENCES `AWARD_TYPE` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MULTIPLIER_ALIAS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MULTIPLIER_ALIAS` ;

CREATE  TABLE IF NOT EXISTS `MULTIPLIER_ALIAS` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `MULTIPLIER_NAME` VARCHAR(32) NOT NULL ,
  `ALIAS` VARCHAR(32) NOT NULL ,
  PRIMARY KEY (`ID`) )
ENGINE = InnoDB;



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `OPERATOR_CATEGORY`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `OPERATOR_CATEGORY` (`ID`, `NAME`) VALUES (1, 'SINGLE-OP');
INSERT INTO `OPERATOR_CATEGORY` (`ID`, `NAME`) VALUES (2, 'MULTI-OP');
INSERT INTO `OPERATOR_CATEGORY` (`ID`, `NAME`) VALUES (3, 'CHECKLOG');

COMMIT;

-- -----------------------------------------------------
-- Data for table `POWER_CATEGORY`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `POWER_CATEGORY` (`ID`, `NAME`) VALUES (1, 'HIGH');
INSERT INTO `POWER_CATEGORY` (`ID`, `NAME`) VALUES (2, 'LOW');
INSERT INTO `POWER_CATEGORY` (`ID`, `NAME`) VALUES (3, 'QRP');

COMMIT;

-- -----------------------------------------------------
-- Data for table `STATION_CATEGORY`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `STATION_CATEGORY` (`ID`, `NAME`) VALUES (1, 'FIXED');
INSERT INTO `STATION_CATEGORY` (`ID`, `NAME`) VALUES (2, 'MOBILE');
INSERT INTO `STATION_CATEGORY` (`ID`, `NAME`) VALUES (3, 'EXPEDITION');
INSERT INTO `STATION_CATEGORY` (`ID`, `NAME`) VALUES (4, 'SCHOOL');

COMMIT;

-- -----------------------------------------------------
-- Data for table `TRANSMITTER_CATEGORY`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `TRANSMITTER_CATEGORY` (`ID`, `NAME`) VALUES (1, 'ONE');
INSERT INTO `TRANSMITTER_CATEGORY` (`ID`, `NAME`) VALUES (2, 'TWO');
INSERT INTO `TRANSMITTER_CATEGORY` (`ID`, `NAME`) VALUES (3, 'UNLIMITED');

COMMIT;

-- -----------------------------------------------------
-- Data for table `QSO_STATUS`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `QSO_STATUS` (`ID`, `NAME`) VALUES (1, 'OK');
INSERT INTO `QSO_STATUS` (`ID`, `NAME`) VALUES (2, 'OKA');
INSERT INTO `QSO_STATUS` (`ID`, `NAME`) VALUES (3, 'OKB');
INSERT INTO `QSO_STATUS` (`ID`, `NAME`) VALUES (4, 'D1A');
INSERT INTO `QSO_STATUS` (`ID`, `NAME`) VALUES (5, 'D1B');
INSERT INTO `QSO_STATUS` (`ID`, `NAME`) VALUES (6, 'D1C');
INSERT INTO `QSO_STATUS` (`ID`, `NAME`) VALUES (7, 'D2A');
INSERT INTO `QSO_STATUS` (`ID`, `NAME`) VALUES (8, 'D2C');
INSERT INTO `QSO_STATUS` (`ID`, `NAME`) VALUES (9, 'U1');
INSERT INTO `QSO_STATUS` (`ID`, `NAME`) VALUES (10, 'U2');
INSERT INTO `QSO_STATUS` (`ID`, `NAME`) VALUES (11, 'BYE');
INSERT INTO `QSO_STATUS` (`ID`, `NAME`) VALUES (12, 'NEW');

COMMIT;

SOURCE multipliers.sql
SOURCE multiplier_alias.sql
