SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL';


-- -----------------------------------------------------
-- Table `OPERATOR_CATEGORY`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `OPERATOR_CATEGORY` (
  `ID` INT NOT NULL ,
  `NAME` VARCHAR(45) NOT NULL ,
  PRIMARY KEY (`ID`) )
ENGINE = InnoDB;

CREATE UNIQUE INDEX `NAME_UNIQUE` ON `OPERATOR_CATEGORY` (`NAME` ASC) ;


-- -----------------------------------------------------
-- Table `POWER_CATEGORY`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `POWER_CATEGORY` (
  `ID` INT NOT NULL ,
  `NAME` VARCHAR(45) NOT NULL ,
  PRIMARY KEY (`ID`) )
ENGINE = InnoDB;

CREATE UNIQUE INDEX `NAME_UNIQUE` ON `POWER_CATEGORY` (`NAME` ASC) ;


-- -----------------------------------------------------
-- Table `STATION_CATEGORY`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `STATION_CATEGORY` (
  `ID` INT NOT NULL ,
  `NAME` VARCHAR(45) NULL ,
  PRIMARY KEY (`ID`) )
ENGINE = InnoDB;

CREATE UNIQUE INDEX `NAME_UNIQUE` ON `STATION_CATEGORY` (`NAME` ASC) ;


-- -----------------------------------------------------
-- Table `OVERLAY_CATEGORY`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `OVERLAY_CATEGORY` (
  `ID` INT NOT NULL ,
  `NAME` VARCHAR(45) NULL ,
  PRIMARY KEY (`ID`) )
ENGINE = InnoDB;

CREATE UNIQUE INDEX `NAME_UNIQUE` ON `OVERLAY_CATEGORY` (`NAME` ASC) ;


-- -----------------------------------------------------
-- Table `TRANSMITTER_CATEGORY`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `TRANSMITTER_CATEGORY` (
  `ID` INT NOT NULL ,
  `NAME` VARCHAR(45) NULL ,
  PRIMARY KEY (`ID`) )
ENGINE = InnoDB;

CREATE UNIQUE INDEX `NAME_UNIQUE` ON `TRANSMITTER_CATEGORY` (`NAME` ASC) ;


-- -----------------------------------------------------
-- Table `OPERATOR`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `OPERATOR` (
  `ID` INT NOT NULL AUTO_INCREMENT ,
  `CALLSIGN` VARCHAR(45) NOT NULL ,
  `CLUB_ID` INT NULL ,
  `CLUB_ALLOCATION` INT NULL ,
  PRIMARY KEY (`ID`) ,
  CONSTRAINT `FK_OPERATOR_LOG`
    FOREIGN KEY (`ID` )
    REFERENCES `LOG` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `FK_OPERATOR_LOG` ON `OPERATOR` (`ID` ASC) ;

CREATE INDEX `FK_OPERATOR_CLUB` ON `OPERATOR` (`CLUB_ID` ASC) ;


-- -----------------------------------------------------
-- Table `CLUB`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `CLUB` (
  `ID` INT NOT NULL ,
  `NAME` VARCHAR(255) NOT NULL ,
  `LOCATION` VARCHAR(45) NOT NULL ,
  PRIMARY KEY (`ID`) ,
  CONSTRAINT `FK_CLUB_OPERATOR`
    FOREIGN KEY (`ID` )
    REFERENCES `OPERATOR` (`CLUB_ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `NAME_UNIQUE` ON `CLUB` (`NAME` ASC) ;

CREATE INDEX `FK_CLUB_OPERATOR` ON `CLUB` (`ID` ASC) ;


-- -----------------------------------------------------
-- Table `LOG`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `LOG` (
  `ID` INT NOT NULL AUTO_INCREMENT ,
  `CONTEST_ID` VARCHAR(45) NOT NULL DEFAULT 'CA-QSO-PARTY' ,
  `STATION_CALLSIGN` VARCHAR(45) NOT NULL ,
  `STATION_OWNER_CALLSIGN` VARCHAR(45) NULL ,
  `STATION_LOCATION` VARCHAR(45) NOT NULL ,
  `CONTEST_YEAR` VARCHAR(4) NOT NULL DEFAULT '2012' ,
  `OPERATOR_CATEGORY` VARCHAR(45) NOT NULL ,
  `POWER_CATEGORY` VARCHAR(45) NOT NULL ,
  `STATION_CATEGORY` VARCHAR(45) NOT NULL ,
  `TRANSMITTER_CATEGORY` VARCHAR(45) NOT NULL ,
  `OVERLAY_CATEGORY` VARCHAR(45) NULL ,
  `CLUB` VARCHAR(255) NULL ,
  `SUBMISSION_DATE` DATE NOT NULL ,
  `CLAIMED_SCORE` VARCHAR(45) NULL ,
  `SCORE` VARCHAR(45) NULL ,
  PRIMARY KEY (`ID`) ,
  CONSTRAINT `FK_LOG_OPERATOR_CATEGORY`
    FOREIGN KEY (`OPERATOR_CATEGORY` )
    REFERENCES `OPERATOR_CATEGORY` (`NAME` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_LOG_POWER_CATEGORY`
    FOREIGN KEY (`POWER_CATEGORY` )
    REFERENCES `POWER_CATEGORY` (`NAME` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_LOG_STATION_CATEGORY`
    FOREIGN KEY (`STATION_CATEGORY` )
    REFERENCES `STATION_CATEGORY` (`NAME` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_LOG_OVERLAY_CATEGORY`
    FOREIGN KEY (`OVERLAY_CATEGORY` )
    REFERENCES `OVERLAY_CATEGORY` (`NAME` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_LOG_TRANSMITTER_CATEGORY`
    FOREIGN KEY (`TRANSMITTER_CATEGORY` )
    REFERENCES `TRANSMITTER_CATEGORY` (`NAME` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_LOG_CLUB`
    FOREIGN KEY (`CLUB` )
    REFERENCES `CLUB` (`NAME` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `FK_LOG_OPERATOR_CATEGORY` ON `LOG` (`OPERATOR_CATEGORY` ASC) ;

CREATE INDEX `FK_LOG_POWER_CATEGORY` ON `LOG` (`POWER_CATEGORY` ASC) ;

CREATE INDEX `FK_LOG_STATION_CATEGORY` ON `LOG` (`STATION_CATEGORY` ASC) ;

CREATE INDEX `FK_LOG_OVERLAY_CATEGORY` ON `LOG` (`OVERLAY_CATEGORY` ASC) ;

CREATE INDEX `FK_LOG_TRANSMITTER_CATEGORY` ON `LOG` (`TRANSMITTER_CATEGORY` ASC) ;

CREATE INDEX `FK_LOG_CLUB` ON `LOG` (`CLUB` ASC) ;


-- -----------------------------------------------------
-- Table `QSO_STATUS`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `QSO_STATUS` (
  `ID` INT NOT NULL ,
  `NAME` VARCHAR(45) NOT NULL ,
  PRIMARY KEY (`ID`) )
ENGINE = InnoDB;

CREATE UNIQUE INDEX `NAME_UNIQUE` ON `QSO_STATUS` (`NAME` ASC) ;


-- -----------------------------------------------------
-- Table `QSO`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `QSO` (
  `ID` INT NULL AUTO_INCREMENT ,
  `LOG_ID` INT NOT NULL ,
  `CALLSIGN` VARCHAR(45) NOT NULL ,
  `QSO_DATE` DATETIME NOT NULL ,
  `FREQUENCY` VARCHAR(45) NOT NULL ,
  `MODE` VARCHAR(45) NOT NULL ,
  `SERIAL_SENT` VARCHAR(45) NOT NULL ,
  `SERIAL_RECIEVED` VARCHAR(45) NOT NULL ,
  `QTH` VARCHAR(45) NOT NULL ,
  `QSO_STATUS` VARCHAR(45) NULL ,
  `LAST_UPDATED` TIMESTAMP NOT NULL DEFAULT current_date ,
  PRIMARY KEY (`ID`) ,
  CONSTRAINT `FK_QSO_LOG`
    FOREIGN KEY (`ID` )
    REFERENCES `LOG` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_QSO_QSO_STATUS`
    FOREIGN KEY (`QSO_STATUS` )
    REFERENCES `QSO_STATUS` (`NAME` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `FK_QSO_LOG` ON `QSO` (`ID` ASC) ;

CREATE INDEX `FK_QSO_QSO_STATUS` ON `QSO` (`QSO_STATUS` ASC) ;



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `OPERATOR_CATEGORY`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `OPERATOR_CATEGORY` (`ID`, `NAME`) VALUES (1, 'SINGLE-OP');
INSERT INTO `OPERATOR_CATEGORY` (`ID`, `NAME`) VALUES (2, 'MULTI-OP');
INSERT INTO `OPERATOR_CATEGORY` (`ID`, `NAME`) VALUES (3, 'CHECKLOG');

COMMIT;

-- -----------------------------------------------------
-- Data for table `POWER_CATEGORY`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `POWER_CATEGORY` (`ID`, `NAME`) VALUES (1, 'HIGH');
INSERT INTO `POWER_CATEGORY` (`ID`, `NAME`) VALUES (2, 'LOW');
INSERT INTO `POWER_CATEGORY` (`ID`, `NAME`) VALUES (3, 'QRP');

COMMIT;

-- -----------------------------------------------------
-- Data for table `STATION_CATEGORY`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `STATION_CATEGORY` (`ID`, `NAME`) VALUES (1, 'FIXED');
INSERT INTO `STATION_CATEGORY` (`ID`, `NAME`) VALUES (2, 'MOBILE');
INSERT INTO `STATION_CATEGORY` (`ID`, `NAME`) VALUES (3, 'EXPEDITION');
INSERT INTO `STATION_CATEGORY` (`ID`, `NAME`) VALUES (4, 'SCHOOL');

COMMIT;

-- -----------------------------------------------------
-- Data for table `OVERLAY_CATEGORY`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `OVERLAY_CATEGORY` (`ID`, `NAME`) VALUES (1, 'YL');
INSERT INTO `OVERLAY_CATEGORY` (`ID`, `NAME`) VALUES (2, 'YOUTH');
INSERT INTO `OVERLAY_CATEGORY` (`ID`, `NAME`) VALUES (3, 'NEW CONTESTER');

COMMIT;

-- -----------------------------------------------------
-- Data for table `QSO_STATUS`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `QSO_STATUS` (`ID`, `NAME`) VALUES (1, 'OK');
INSERT INTO `QSO_STATUS` (`ID`, `NAME`) VALUES (2, 'OKA');
INSERT INTO `QSO_STATUS` (`ID`, `NAME`) VALUES (3, 'OKB');
INSERT INTO `QSO_STATUS` (`ID`, `NAME`) VALUES (4, 'D1A');
INSERT INTO `QSO_STATUS` (`ID`, `NAME`) VALUES (5, 'D1B');
INSERT INTO `QSO_STATUS` (`ID`, `NAME`) VALUES (6, 'D1C');
INSERT INTO `QSO_STATUS` (`ID`, `NAME`) VALUES (7, 'D2A');
INSERT INTO `QSO_STATUS` (`ID`, `NAME`) VALUES (8, 'D2C');
INSERT INTO `QSO_STATUS` (`ID`, `NAME`) VALUES (9, 'U1');
INSERT INTO `QSO_STATUS` (`ID`, `NAME`) VALUES (10, 'U2');
INSERT INTO `QSO_STATUS` (`ID`, `NAME`) VALUES (11, 'BYE');
INSERT INTO `QSO_STATUS` (`ID`, `NAME`) VALUES (12, NULL);

COMMIT;
