insert into MULTIPLIER_ALIAS (MULTIPLIER_NAME,ALIAS) values ('MR','NB');
insert into MULTIPLIER_ALIAS (MULTIPLIER_NAME,ALIAS) values ('MR','NL');
insert into MULTIPLIER_ALIAS (MULTIPLIER_NAME,ALIAS) values ('MR','NS');
insert into MULTIPLIER_ALIAS (MULTIPLIER_NAME,ALIAS) values ('MR','PE');
insert into MULTIPLIER_ALIAS (MULTIPLIER_NAME,ALIAS) values ('MR','MAR');
insert into MULTIPLIER_ALIAS (MULTIPLIER_NAME,ALIAS) values ('NT','NU');
insert into MULTIPLIER_ALIAS (MULTIPLIER_NAME,ALIAS) values ('NT','YT');
insert into MULTIPLIER_ALIAS (MULTIPLIER_NAME,ALIAS) values ('MD','MDC');
commit;
